extend type Account {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Account", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Account`.`user`. It must match the value of `Fam`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Account.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Availability {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Availability", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Availability`.`fam`. It must match the value of `Fam`.`id`. See `@ref` for how to customize it.
  """
  famId: UUID! @fdc_generated(from: "Availability.fam", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Availability`.`meetup`. It must match the value of `Meetup`.`id`. See `@ref` for how to customize it.
  """
  meetupId: UUID! @fdc_generated(from: "Availability.meetup", purpose: IMPLICIT_REF_FIELD)
}
extend type Fam {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Fam", purpose: IMPLICIT_KEY_FIELD)
}
extend type Meetup {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Meetup", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Meetup`.`host`. It must match the value of `Fam`.`id`. See `@ref` for how to customize it.
  """
  hostId: UUID! @fdc_generated(from: "Meetup.host", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Meetup`.`tribe`. It must match the value of `Tribe`.`id`. See `@ref` for how to customize it.
  """
  tribeId: UUID! @fdc_generated(from: "Meetup.tribe", purpose: IMPLICIT_REF_FIELD)
}
extend type Tribe {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Tribe", purpose: IMPLICIT_KEY_FIELD)
}
extend type TribeFam {
  """
  ✨ Implicit foreign key field based on `TribeFam`.`tribe`. It must match the value of `Tribe`.`id`. See `@ref` for how to customize it.
  """
  tribeId: UUID! @fdc_generated(from: "TribeFam.tribe", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `TribeFam`.`fam`. It must match the value of `Fam`.`id`. See `@ref` for how to customize it.
  """
  famId: UUID! @fdc_generated(from: "TribeFam.fam", purpose: IMPLICIT_REF_FIELD)
}
extend type UserDevice {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "UserDevice", purpose: IMPLICIT_KEY_FIELD)
}
