"""
✨ `Availability_KeyOutput` returns the primary key fields of table type `Availability`.

It has the same format as `Availability_Key`, but is only used as mutation return value.
"""
scalar Availability_KeyOutput
"""
✨ `Chat_KeyOutput` returns the primary key fields of table type `Chat`.

It has the same format as `Chat_Key`, but is only used as mutation return value.
"""
scalar Chat_KeyOutput
"""
✨ `ChatMember_KeyOutput` returns the primary key fields of table type `ChatMember`.

It has the same format as `ChatMember_Key`, but is only used as mutation return value.
"""
scalar ChatMember_KeyOutput
"""
✨ `Meetup_KeyOutput` returns the primary key fields of table type `Meetup`.

It has the same format as `Meetup_Key`, but is only used as mutation return value.
"""
scalar Meetup_KeyOutput
"""
✨ `Member_KeyOutput` returns the primary key fields of table type `Member`.

It has the same format as `Member_Key`, but is only used as mutation return value.
"""
scalar Member_KeyOutput
"""
✨ `MemberAlertPreference_KeyOutput` returns the primary key fields of table type `MemberAlertPreference`.

It has the same format as `MemberAlertPreference_Key`, but is only used as mutation return value.
"""
scalar MemberAlertPreference_KeyOutput
"""
✨ `MemberContact_KeyOutput` returns the primary key fields of table type `MemberContact`.

It has the same format as `MemberContact_Key`, but is only used as mutation return value.
"""
scalar MemberContact_KeyOutput
"""
✨ `Notification_KeyOutput` returns the primary key fields of table type `Notification`.

It has the same format as `Notification_Key`, but is only used as mutation return value.
"""
scalar Notification_KeyOutput
"""
✨ `Proposal_KeyOutput` returns the primary key fields of table type `Proposal`.

It has the same format as `Proposal_Key`, but is only used as mutation return value.
"""
scalar Proposal_KeyOutput
"""
✨ `Tribe_KeyOutput` returns the primary key fields of table type `Tribe`.

It has the same format as `Tribe_Key`, but is only used as mutation return value.
"""
scalar Tribe_KeyOutput
"""
✨ `TribeMember_KeyOutput` returns the primary key fields of table type `TribeMember`.

It has the same format as `TribeMember_Key`, but is only used as mutation return value.
"""
scalar TribeMember_KeyOutput
"""
✨ `UserDevice_KeyOutput` returns the primary key fields of table type `UserDevice`.

It has the same format as `UserDevice_Key`, but is only used as mutation return value.
"""
scalar UserDevice_KeyOutput
"""
✨ Generated data input type for table 'Availability'. It includes all necessary fields for creating or upserting rows into table.
"""
input Availability_Data {
  """
  ✨ Generated from Field `Availability`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Availability`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`memberId` of type `UUID!`
  """
  memberId: UUID
  """
  ✨ `_expr` server value variant of `memberId` (✨ Generated from Field `Availability`.`memberId` of type `UUID!`)
  """
  memberId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`proposalId` of type `UUID!`
  """
  proposalId: UUID
  """
  ✨ `_expr` server value variant of `proposalId` (✨ Generated from Field `Availability`.`proposalId` of type `UUID!`)
  """
  proposalId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`member` of type `Member!`
  """
  member: Member_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`proposal` of type `Proposal!`
  """
  proposal: Proposal_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`note` of type `String`
  """
  note: String
  """
  ✨ `_expr` server value variant of `note` (✨ Generated from Field `Availability`.`note` of type `String`)
  """
  note_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `Availability`.`status` of type `String!`)
  """
  status_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`vote` of type `Boolean`
  """
  vote: Boolean
  """
  ✨ `_expr` server value variant of `vote` (✨ Generated from Field `Availability`.`vote` of type `Boolean`)
  """
  vote_expr: Boolean_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Availability'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Availability_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Availability_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Availability_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Availability_Filter!]
  """
  ✨ Generated from Field `Availability`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Availability`.`memberId` of type `UUID!`
  """
  memberId: UUID_Filter
  """
  ✨ Generated from Field `Availability`.`proposalId` of type `UUID!`
  """
  proposalId: UUID_Filter
  """
  ✨ Generated from Field `Availability`.`member` of type `Member!`
  """
  member: Member_Filter
  """
  ✨ Generated from Field `Availability`.`proposal` of type `Proposal!`
  """
  proposal: Proposal_Filter
  """
  ✨ Generated from Field `Availability`.`note` of type `String`
  """
  note: String_Filter
  """
  ✨ Generated from Field `Availability`.`status` of type `String!`
  """
  status: String_Filter
  """
  ✨ Generated from Field `Availability`.`vote` of type `Boolean`
  """
  vote: Boolean_Filter
}
"""
✨ Generated first-row input type for table 'Availability'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Availability_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Availability_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Availability_Filter
}
"""
✨ Generated having input type for table 'Availability'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Availability_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Availability_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Availability_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Availability_Having!]
  """
  ✨ Generated from Field `Availability`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`memberId_count` of type `Int!`
  """
  memberId_count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`note_count` of type `Int!`
  """
  note_count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`proposalId_count` of type `Int!`
  """
  proposalId_count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`vote_count` of type `Int!`
  """
  vote_count: Int_Filter
}
"""
✨ Generated key input type for table 'Availability'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Availability_Key {
  """
  ✨ Generated from Field `Availability`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Availability`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Availability'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Availability_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Availability_Filter
}
"""
✨ Generated order input type for table 'Availability'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Availability_Order {
  """
  ✨ Generated from Field `Availability`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Availability`.`memberId` of type `UUID!`
  """
  memberId: OrderDirection
  """
  ✨ Generated from Field `Availability`.`proposalId` of type `UUID!`
  """
  proposalId: OrderDirection
  """
  ✨ Generated from Field `Availability`.`member` of type `Member!`
  """
  member: Member_Order
  """
  ✨ Generated from Field `Availability`.`proposal` of type `Proposal!`
  """
  proposal: Proposal_Order
  """
  ✨ Generated from Field `Availability`.`note` of type `String`
  """
  note: OrderDirection
  """
  ✨ Generated from Field `Availability`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `Availability`.`vote` of type `Boolean`
  """
  vote: OrderDirection
  """
  ✨ Generated from Field `Availability`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`memberId_count` of type `Int!`
  """
  memberId_count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`note_count` of type `Int!`
  """
  note_count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`proposalId_count` of type `Int!`
  """
  proposalId_count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`vote_count` of type `Int!`
  """
  vote_count: OrderDirection
}
"""
✨ Generated data input type for table 'Chat'. It includes all necessary fields for creating or upserting rows into table.
"""
input Chat_Data {
  """
  ✨ Generated from Field `Chat`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Chat`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Chat`.`name` of type `String`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Chat`.`name` of type `String`)
  """
  name_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Chat`.`url` of type `String`
  """
  url: String
  """
  ✨ `_expr` server value variant of `url` (✨ Generated from Field `Chat`.`url` of type `String`)
  """
  url_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Chat'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Chat_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Chat_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Chat_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Chat_Filter!]
  """
  ✨ Generated from Field `Chat`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Chat`.`name` of type `String`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Chat`.`url` of type `String`
  """
  url: String_Filter
  """
  ✨ Generated from Field `Chat`.`chatMembers_on_chat` of type `[ChatMember!]!`
  """
  chatMembers_on_chat: ChatMember_ListFilter
}
"""
✨ Generated first-row input type for table 'Chat'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Chat_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Chat_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Chat_Filter
}
"""
✨ Generated having input type for table 'Chat'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Chat_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Chat_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Chat_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Chat_Having!]
  """
  ✨ Generated from Field `Chat`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Chat`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Chat`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Chat`.`url_count` of type `Int!`
  """
  url_count: Int_Filter
}
"""
✨ Generated key input type for table 'Chat'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Chat_Key {
  """
  ✨ Generated from Field `Chat`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Chat`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Chat'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Chat_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Chat_Filter
}
"""
✨ Generated order input type for table 'Chat'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Chat_Order {
  """
  ✨ Generated from Field `Chat`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Chat`.`name` of type `String`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Chat`.`url` of type `String`
  """
  url: OrderDirection
  """
  ✨ Generated from Field `Chat`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Chat`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Chat`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Chat`.`url_count` of type `Int!`
  """
  url_count: OrderDirection
}
"""
✨ Generated data input type for table 'ChatMember'. It includes all necessary fields for creating or upserting rows into table.
"""
input ChatMember_Data {
  """
  ✨ Generated from Field `ChatMember`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `ChatMember`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ChatMember`.`chatId` of type `UUID!`
  """
  chatId: UUID
  """
  ✨ `_expr` server value variant of `chatId` (✨ Generated from Field `ChatMember`.`chatId` of type `UUID!`)
  """
  chatId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ChatMember`.`memberId` of type `UUID!`
  """
  memberId: UUID
  """
  ✨ `_expr` server value variant of `memberId` (✨ Generated from Field `ChatMember`.`memberId` of type `UUID!`)
  """
  memberId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ChatMember`.`chat` of type `Chat!`
  """
  chat: Chat_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ChatMember`.`member` of type `Member!`
  """
  member: Member_Key @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'ChatMember'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input ChatMember_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [ChatMember_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: ChatMember_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [ChatMember_Filter!]
  """
  ✨ Generated from Field `ChatMember`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `ChatMember`.`chatId` of type `UUID!`
  """
  chatId: UUID_Filter
  """
  ✨ Generated from Field `ChatMember`.`memberId` of type `UUID!`
  """
  memberId: UUID_Filter
  """
  ✨ Generated from Field `ChatMember`.`chat` of type `Chat!`
  """
  chat: Chat_Filter
  """
  ✨ Generated from Field `ChatMember`.`member` of type `Member!`
  """
  member: Member_Filter
}
"""
✨ Generated first-row input type for table 'ChatMember'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input ChatMember_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [ChatMember_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: ChatMember_Filter
}
"""
✨ Generated having input type for table 'ChatMember'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input ChatMember_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [ChatMember_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: ChatMember_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [ChatMember_Having!]
  """
  ✨ Generated from Field `ChatMember`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `ChatMember`.`chatId_count` of type `Int!`
  """
  chatId_count: Int_Filter
  """
  ✨ Generated from Field `ChatMember`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `ChatMember`.`memberId_count` of type `Int!`
  """
  memberId_count: Int_Filter
}
"""
✨ Generated key input type for table 'ChatMember'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input ChatMember_Key {
  """
  ✨ Generated from Field `ChatMember`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `ChatMember`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'ChatMember'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input ChatMember_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: ChatMember_Filter
}
"""
✨ Generated order input type for table 'ChatMember'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input ChatMember_Order {
  """
  ✨ Generated from Field `ChatMember`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `ChatMember`.`chatId` of type `UUID!`
  """
  chatId: OrderDirection
  """
  ✨ Generated from Field `ChatMember`.`memberId` of type `UUID!`
  """
  memberId: OrderDirection
  """
  ✨ Generated from Field `ChatMember`.`chat` of type `Chat!`
  """
  chat: Chat_Order
  """
  ✨ Generated from Field `ChatMember`.`member` of type `Member!`
  """
  member: Member_Order
  """
  ✨ Generated from Field `ChatMember`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `ChatMember`.`chatId_count` of type `Int!`
  """
  chatId_count: OrderDirection
  """
  ✨ Generated from Field `ChatMember`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `ChatMember`.`memberId_count` of type `Int!`
  """
  memberId_count: OrderDirection
}
"""
✨ Generated data input type for table 'Meetup'. It includes all necessary fields for creating or upserting rows into table.
"""
input Meetup_Data {
  """
  ✨ Generated from Field `Meetup`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Meetup`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`creatorId` of type `UUID!`
  """
  creatorId: UUID
  """
  ✨ `_expr` server value variant of `creatorId` (✨ Generated from Field `Meetup`.`creatorId` of type `UUID!`)
  """
  creatorId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`tribeId` of type `UUID!`
  """
  tribeId: UUID
  """
  ✨ `_expr` server value variant of `tribeId` (✨ Generated from Field `Meetup`.`tribeId` of type `UUID!`)
  """
  tribeId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`creator` of type `Member!`
  """
  creator: Member_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Meetup`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Meetup`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Meetup`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`daysToDecide` of type `Int!`
  """
  daysToDecide: Int
  """
  ✨ `_expr` server value variant of `daysToDecide` (✨ Generated from Field `Meetup`.`daysToDecide` of type `Int!`)
  """
  daysToDecide_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `daysToDecide` (✨ Generated from Field `Meetup`.`daysToDecide` of type `Int!`)
  """
  daysToDecide_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`decisionMethod` of type `String!`
  """
  decisionMethod: String
  """
  ✨ `_expr` server value variant of `decisionMethod` (✨ Generated from Field `Meetup`.`decisionMethod` of type `String!`)
  """
  decisionMethod_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`details` of type `String`
  """
  details: String
  """
  ✨ `_expr` server value variant of `details` (✨ Generated from Field `Meetup`.`details` of type `String`)
  """
  details_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`eventType` of type `String`
  """
  eventType: String
  """
  ✨ `_expr` server value variant of `eventType` (✨ Generated from Field `Meetup`.`eventType` of type `String`)
  """
  eventType_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`iconType` of type `String`
  """
  iconType: String
  """
  ✨ `_expr` server value variant of `iconType` (✨ Generated from Field `Meetup`.`iconType` of type `String`)
  """
  iconType_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays` of type `Int`
  """
  recursEveryDays: Int
  """
  ✨ `_expr` server value variant of `recursEveryDays` (✨ Generated from Field `Meetup`.`recursEveryDays` of type `Int`)
  """
  recursEveryDays_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `recursEveryDays` (✨ Generated from Field `Meetup`.`recursEveryDays` of type `Int`)
  """
  recursEveryDays_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `Meetup`.`status` of type `String!`)
  """
  status_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`title` of type `String`
  """
  title: String
  """
  ✨ `_expr` server value variant of `title` (✨ Generated from Field `Meetup`.`title` of type `String`)
  """
  title_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Meetup'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Meetup_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Meetup_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Meetup_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Meetup_Filter!]
  """
  ✨ Generated from Field `Meetup`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Meetup`.`creatorId` of type `UUID!`
  """
  creatorId: UUID_Filter
  """
  ✨ Generated from Field `Meetup`.`tribeId` of type `UUID!`
  """
  tribeId: UUID_Filter
  """
  ✨ Generated from Field `Meetup`.`creator` of type `Member!`
  """
  creator: Member_Filter
  """
  ✨ Generated from Field `Meetup`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Filter
  """
  ✨ Generated from Field `Meetup`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Meetup`.`daysToDecide` of type `Int!`
  """
  daysToDecide: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`decisionMethod` of type `String!`
  """
  decisionMethod: String_Filter
  """
  ✨ Generated from Field `Meetup`.`details` of type `String`
  """
  details: String_Filter
  """
  ✨ Generated from Field `Meetup`.`eventType` of type `String`
  """
  eventType: String_Filter
  """
  ✨ Generated from Field `Meetup`.`iconType` of type `String`
  """
  iconType: String_Filter
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays` of type `Int`
  """
  recursEveryDays: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`status` of type `String!`
  """
  status: String_Filter
  """
  ✨ Generated from Field `Meetup`.`title` of type `String`
  """
  title: String_Filter
  """
  ✨ Generated from Field `Meetup`.`proposals_on_meetup` of type `[Proposal!]!`
  """
  proposals_on_meetup: Proposal_ListFilter
}
"""
✨ Generated first-row input type for table 'Meetup'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Meetup_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Meetup_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Meetup_Filter
}
"""
✨ Generated having input type for table 'Meetup'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Meetup_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Meetup_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Meetup_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Meetup_Having!]
  """
  ✨ Generated from Field `Meetup`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`creatorId_count` of type `Int!`
  """
  creatorId_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`daysToDecide_count` of type `Int!`
  """
  daysToDecide_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`decisionMethod_count` of type `Int!`
  """
  decisionMethod_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`details_count` of type `Int!`
  """
  details_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`eventType_count` of type `Int!`
  """
  eventType_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`iconType_count` of type `Int!`
  """
  iconType_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays_count` of type `Int!`
  """
  recursEveryDays_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`title_count` of type `Int!`
  """
  title_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`tribeId_count` of type `Int!`
  """
  tribeId_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`daysToDecide_sum` of type `Int`
  """
  daysToDecide_sum: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays_sum` of type `Int`
  """
  recursEveryDays_sum: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`daysToDecide_avg` of type `Float`
  """
  daysToDecide_avg: Float_Filter
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays_avg` of type `Float`
  """
  recursEveryDays_avg: Float_Filter
  """
  ✨ Generated from Field `Meetup`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Meetup`.`daysToDecide_min` of type `Int`
  """
  daysToDecide_min: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays_min` of type `Int`
  """
  recursEveryDays_min: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Meetup`.`daysToDecide_max` of type `Int`
  """
  daysToDecide_max: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays_max` of type `Int`
  """
  recursEveryDays_max: Int_Filter
}
"""
✨ Generated key input type for table 'Meetup'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Meetup_Key {
  """
  ✨ Generated from Field `Meetup`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Meetup`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Meetup'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Meetup_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Meetup_Filter
}
"""
✨ Generated order input type for table 'Meetup'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Meetup_Order {
  """
  ✨ Generated from Field `Meetup`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`creatorId` of type `UUID!`
  """
  creatorId: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`tribeId` of type `UUID!`
  """
  tribeId: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`creator` of type `Member!`
  """
  creator: Member_Order
  """
  ✨ Generated from Field `Meetup`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Order
  """
  ✨ Generated from Field `Meetup`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`daysToDecide` of type `Int!`
  """
  daysToDecide: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`decisionMethod` of type `String!`
  """
  decisionMethod: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`details` of type `String`
  """
  details: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`eventType` of type `String`
  """
  eventType: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`iconType` of type `String`
  """
  iconType: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays` of type `Int`
  """
  recursEveryDays: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`title` of type `String`
  """
  title: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`creatorId_count` of type `Int!`
  """
  creatorId_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`daysToDecide_count` of type `Int!`
  """
  daysToDecide_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`decisionMethod_count` of type `Int!`
  """
  decisionMethod_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`details_count` of type `Int!`
  """
  details_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`eventType_count` of type `Int!`
  """
  eventType_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`iconType_count` of type `Int!`
  """
  iconType_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays_count` of type `Int!`
  """
  recursEveryDays_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`title_count` of type `Int!`
  """
  title_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`tribeId_count` of type `Int!`
  """
  tribeId_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`daysToDecide_sum` of type `Int`
  """
  daysToDecide_sum: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays_sum` of type `Int`
  """
  recursEveryDays_sum: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`daysToDecide_avg` of type `Float`
  """
  daysToDecide_avg: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays_avg` of type `Float`
  """
  recursEveryDays_avg: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`daysToDecide_min` of type `Int`
  """
  daysToDecide_min: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays_min` of type `Int`
  """
  recursEveryDays_min: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`daysToDecide_max` of type `Int`
  """
  daysToDecide_max: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`recursEveryDays_max` of type `Int`
  """
  recursEveryDays_max: OrderDirection
}
"""
✨ Generated data input type for table 'Member'. It includes all necessary fields for creating or upserting rows into table.
"""
input Member_Data {
  """
  ✨ Generated from Field `Member`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Member`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Member`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `Member`.`email` of type `String!`)
  """
  email_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Member`.`mapType` of type `String`
  """
  mapType: String
  """
  ✨ `_expr` server value variant of `mapType` (✨ Generated from Field `Member`.`mapType` of type `String`)
  """
  mapType_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Member`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Member`.`name` of type `String!`)
  """
  name_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Member`.`phone` of type `String!`
  """
  phone: String
  """
  ✨ `_expr` server value variant of `phone` (✨ Generated from Field `Member`.`phone` of type `String!`)
  """
  phone_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Member`.`profilePicData` of type `String`
  """
  profilePicData: String
  """
  ✨ `_expr` server value variant of `profilePicData` (✨ Generated from Field `Member`.`profilePicData` of type `String`)
  """
  profilePicData_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Member`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `Member`.`status` of type `String!`)
  """
  status_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Member`.`userId` of type `String`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Member`.`userId` of type `String`)
  """
  userId_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Member'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Member_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Member_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Member_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Member_Filter!]
  """
  ✨ Generated from Field `Member`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Member`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `Member`.`mapType` of type `String`
  """
  mapType: String_Filter
  """
  ✨ Generated from Field `Member`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Member`.`phone` of type `String!`
  """
  phone: String_Filter
  """
  ✨ Generated from Field `Member`.`profilePicData` of type `String`
  """
  profilePicData: String_Filter
  """
  ✨ Generated from Field `Member`.`status` of type `String!`
  """
  status: String_Filter
  """
  ✨ Generated from Field `Member`.`userId` of type `String`
  """
  userId: String_Filter
  """
  ✨ Generated from Field `Member`.`availabilities_on_member` of type `[Availability!]!`
  """
  availabilities_on_member: Availability_ListFilter
  """
  ✨ Generated from Field `Member`.`chatMembers_on_member` of type `[ChatMember!]!`
  """
  chatMembers_on_member: ChatMember_ListFilter
  """
  ✨ Generated from Field `Member`.`meetups_on_creator` of type `[Meetup!]!`
  """
  meetups_on_creator: Meetup_ListFilter
  """
  ✨ Generated from Field `Member`.`memberAlertPreferences_on_member` of type `[MemberAlertPreference!]!`
  """
  memberAlertPreferences_on_member: MemberAlertPreference_ListFilter
  """
  ✨ Generated from Field `Member`.`memberContacts_on_source` of type `[MemberContact!]!`
  """
  memberContacts_on_source: MemberContact_ListFilter
  """
  ✨ Generated from Field `Member`.`memberContacts_on_subject` of type `[MemberContact!]!`
  """
  memberContacts_on_subject: MemberContact_ListFilter
  """
  ✨ Generated from Field `Member`.`notifications_on_member` of type `[Notification!]!`
  """
  notifications_on_member: Notification_ListFilter
  """
  ✨ Generated from Field `Member`.`proposals_on_host` of type `[Proposal!]!`
  """
  proposals_on_host: Proposal_ListFilter
  """
  ✨ Generated from Field `Member`.`tribeMembers_on_member` of type `[TribeMember!]!`
  """
  tribeMembers_on_member: TribeMember_ListFilter
}
"""
✨ Generated first-row input type for table 'Member'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Member_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Member_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Member_Filter
}
"""
✨ Generated having input type for table 'Member'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Member_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Member_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Member_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Member_Having!]
  """
  ✨ Generated from Field `Member`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Member`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `Member`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Member`.`mapType_count` of type `Int!`
  """
  mapType_count: Int_Filter
  """
  ✨ Generated from Field `Member`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Member`.`phone_count` of type `Int!`
  """
  phone_count: Int_Filter
  """
  ✨ Generated from Field `Member`.`profilePicData_count` of type `Int!`
  """
  profilePicData_count: Int_Filter
  """
  ✨ Generated from Field `Member`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `Member`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
}
"""
✨ Generated key input type for table 'Member'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Member_Key {
  """
  ✨ Generated from Field `Member`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Member`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Member'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Member_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Member_Filter
}
"""
✨ Generated order input type for table 'Member'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Member_Order {
  """
  ✨ Generated from Field `Member`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Member`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `Member`.`mapType` of type `String`
  """
  mapType: OrderDirection
  """
  ✨ Generated from Field `Member`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Member`.`phone` of type `String!`
  """
  phone: OrderDirection
  """
  ✨ Generated from Field `Member`.`profilePicData` of type `String`
  """
  profilePicData: OrderDirection
  """
  ✨ Generated from Field `Member`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `Member`.`userId` of type `String`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `Member`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Member`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `Member`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Member`.`mapType_count` of type `Int!`
  """
  mapType_count: OrderDirection
  """
  ✨ Generated from Field `Member`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Member`.`phone_count` of type `Int!`
  """
  phone_count: OrderDirection
  """
  ✨ Generated from Field `Member`.`profilePicData_count` of type `Int!`
  """
  profilePicData_count: OrderDirection
  """
  ✨ Generated from Field `Member`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `Member`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
}
"""
✨ Generated data input type for table 'MemberAlertPreference'. It includes all necessary fields for creating or upserting rows into table.
"""
input MemberAlertPreference_Data {
  """
  ✨ Generated from Field `MemberAlertPreference`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `MemberAlertPreference`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `MemberAlertPreference`.`memberId` of type `UUID!`
  """
  memberId: UUID
  """
  ✨ `_expr` server value variant of `memberId` (✨ Generated from Field `MemberAlertPreference`.`memberId` of type `UUID!`)
  """
  memberId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `MemberAlertPreference`.`member` of type `Member!`
  """
  member: Member_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `MemberAlertPreference`.`alertType` of type `String!`
  """
  alertType: String
  """
  ✨ `_expr` server value variant of `alertType` (✨ Generated from Field `MemberAlertPreference`.`alertType` of type `String!`)
  """
  alertType_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `MemberAlertPreference`.`emailEnabled` of type `Boolean!`
  """
  emailEnabled: Boolean
  """
  ✨ `_expr` server value variant of `emailEnabled` (✨ Generated from Field `MemberAlertPreference`.`emailEnabled` of type `Boolean!`)
  """
  emailEnabled_expr: Boolean_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `MemberAlertPreference`.`pushEnabled` of type `Boolean!`
  """
  pushEnabled: Boolean
  """
  ✨ `_expr` server value variant of `pushEnabled` (✨ Generated from Field `MemberAlertPreference`.`pushEnabled` of type `Boolean!`)
  """
  pushEnabled_expr: Boolean_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'MemberAlertPreference'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input MemberAlertPreference_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [MemberAlertPreference_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: MemberAlertPreference_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [MemberAlertPreference_Filter!]
  """
  ✨ Generated from Field `MemberAlertPreference`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `MemberAlertPreference`.`memberId` of type `UUID!`
  """
  memberId: UUID_Filter
  """
  ✨ Generated from Field `MemberAlertPreference`.`member` of type `Member!`
  """
  member: Member_Filter
  """
  ✨ Generated from Field `MemberAlertPreference`.`alertType` of type `String!`
  """
  alertType: String_Filter
  """
  ✨ Generated from Field `MemberAlertPreference`.`emailEnabled` of type `Boolean!`
  """
  emailEnabled: Boolean_Filter
  """
  ✨ Generated from Field `MemberAlertPreference`.`pushEnabled` of type `Boolean!`
  """
  pushEnabled: Boolean_Filter
}
"""
✨ Generated first-row input type for table 'MemberAlertPreference'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input MemberAlertPreference_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [MemberAlertPreference_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: MemberAlertPreference_Filter
}
"""
✨ Generated having input type for table 'MemberAlertPreference'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input MemberAlertPreference_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [MemberAlertPreference_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: MemberAlertPreference_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [MemberAlertPreference_Having!]
  """
  ✨ Generated from Field `MemberAlertPreference`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `MemberAlertPreference`.`alertType_count` of type `Int!`
  """
  alertType_count: Int_Filter
  """
  ✨ Generated from Field `MemberAlertPreference`.`emailEnabled_count` of type `Int!`
  """
  emailEnabled_count: Int_Filter
  """
  ✨ Generated from Field `MemberAlertPreference`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `MemberAlertPreference`.`memberId_count` of type `Int!`
  """
  memberId_count: Int_Filter
  """
  ✨ Generated from Field `MemberAlertPreference`.`pushEnabled_count` of type `Int!`
  """
  pushEnabled_count: Int_Filter
}
"""
✨ Generated key input type for table 'MemberAlertPreference'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input MemberAlertPreference_Key {
  """
  ✨ Generated from Field `MemberAlertPreference`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `MemberAlertPreference`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'MemberAlertPreference'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input MemberAlertPreference_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: MemberAlertPreference_Filter
}
"""
✨ Generated order input type for table 'MemberAlertPreference'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input MemberAlertPreference_Order {
  """
  ✨ Generated from Field `MemberAlertPreference`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `MemberAlertPreference`.`memberId` of type `UUID!`
  """
  memberId: OrderDirection
  """
  ✨ Generated from Field `MemberAlertPreference`.`member` of type `Member!`
  """
  member: Member_Order
  """
  ✨ Generated from Field `MemberAlertPreference`.`alertType` of type `String!`
  """
  alertType: OrderDirection
  """
  ✨ Generated from Field `MemberAlertPreference`.`emailEnabled` of type `Boolean!`
  """
  emailEnabled: OrderDirection
  """
  ✨ Generated from Field `MemberAlertPreference`.`pushEnabled` of type `Boolean!`
  """
  pushEnabled: OrderDirection
  """
  ✨ Generated from Field `MemberAlertPreference`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `MemberAlertPreference`.`alertType_count` of type `Int!`
  """
  alertType_count: OrderDirection
  """
  ✨ Generated from Field `MemberAlertPreference`.`emailEnabled_count` of type `Int!`
  """
  emailEnabled_count: OrderDirection
  """
  ✨ Generated from Field `MemberAlertPreference`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `MemberAlertPreference`.`memberId_count` of type `Int!`
  """
  memberId_count: OrderDirection
  """
  ✨ Generated from Field `MemberAlertPreference`.`pushEnabled_count` of type `Int!`
  """
  pushEnabled_count: OrderDirection
}
"""
✨ Generated data input type for table 'MemberContact'. It includes all necessary fields for creating or upserting rows into table.
"""
input MemberContact_Data {
  """
  ✨ Generated from Field `MemberContact`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `MemberContact`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `MemberContact`.`sourceId` of type `UUID!`
  """
  sourceId: UUID
  """
  ✨ `_expr` server value variant of `sourceId` (✨ Generated from Field `MemberContact`.`sourceId` of type `UUID!`)
  """
  sourceId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `MemberContact`.`subjectId` of type `UUID!`
  """
  subjectId: UUID
  """
  ✨ `_expr` server value variant of `subjectId` (✨ Generated from Field `MemberContact`.`subjectId` of type `UUID!`)
  """
  subjectId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `MemberContact`.`source` of type `Member!`
  """
  source: Member_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `MemberContact`.`subject` of type `Member!`
  """
  subject: Member_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `MemberContact`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `MemberContact`.`status` of type `String!`)
  """
  status_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'MemberContact'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input MemberContact_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [MemberContact_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: MemberContact_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [MemberContact_Filter!]
  """
  ✨ Generated from Field `MemberContact`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `MemberContact`.`sourceId` of type `UUID!`
  """
  sourceId: UUID_Filter
  """
  ✨ Generated from Field `MemberContact`.`subjectId` of type `UUID!`
  """
  subjectId: UUID_Filter
  """
  ✨ Generated from Field `MemberContact`.`source` of type `Member!`
  """
  source: Member_Filter
  """
  ✨ Generated from Field `MemberContact`.`subject` of type `Member!`
  """
  subject: Member_Filter
  """
  ✨ Generated from Field `MemberContact`.`status` of type `String!`
  """
  status: String_Filter
}
"""
✨ Generated first-row input type for table 'MemberContact'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input MemberContact_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [MemberContact_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: MemberContact_Filter
}
"""
✨ Generated having input type for table 'MemberContact'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input MemberContact_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [MemberContact_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: MemberContact_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [MemberContact_Having!]
  """
  ✨ Generated from Field `MemberContact`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `MemberContact`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `MemberContact`.`sourceId_count` of type `Int!`
  """
  sourceId_count: Int_Filter
  """
  ✨ Generated from Field `MemberContact`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `MemberContact`.`subjectId_count` of type `Int!`
  """
  subjectId_count: Int_Filter
}
"""
✨ Generated key input type for table 'MemberContact'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input MemberContact_Key {
  """
  ✨ Generated from Field `MemberContact`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `MemberContact`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'MemberContact'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input MemberContact_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: MemberContact_Filter
}
"""
✨ Generated order input type for table 'MemberContact'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input MemberContact_Order {
  """
  ✨ Generated from Field `MemberContact`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `MemberContact`.`sourceId` of type `UUID!`
  """
  sourceId: OrderDirection
  """
  ✨ Generated from Field `MemberContact`.`subjectId` of type `UUID!`
  """
  subjectId: OrderDirection
  """
  ✨ Generated from Field `MemberContact`.`source` of type `Member!`
  """
  source: Member_Order
  """
  ✨ Generated from Field `MemberContact`.`subject` of type `Member!`
  """
  subject: Member_Order
  """
  ✨ Generated from Field `MemberContact`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `MemberContact`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `MemberContact`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `MemberContact`.`sourceId_count` of type `Int!`
  """
  sourceId_count: OrderDirection
  """
  ✨ Generated from Field `MemberContact`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `MemberContact`.`subjectId_count` of type `Int!`
  """
  subjectId_count: OrderDirection
}
"""
✨ Generated data input type for table 'Notification'. It includes all necessary fields for creating or upserting rows into table.
"""
input Notification_Data {
  """
  ✨ Generated from Field `Notification`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Notification`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`memberId` of type `UUID!`
  """
  memberId: UUID
  """
  ✨ `_expr` server value variant of `memberId` (✨ Generated from Field `Notification`.`memberId` of type `UUID!`)
  """
  memberId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`member` of type `Member!`
  """
  member: Member_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`actionMode` of type `String`
  """
  actionMode: String
  """
  ✨ `_expr` server value variant of `actionMode` (✨ Generated from Field `Notification`.`actionMode` of type `String`)
  """
  actionMode_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`body` of type `String!`
  """
  body: String
  """
  ✨ `_expr` server value variant of `body` (✨ Generated from Field `Notification`.`body` of type `String!`)
  """
  body_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`htmlBody` of type `String`
  """
  htmlBody: String
  """
  ✨ `_expr` server value variant of `htmlBody` (✨ Generated from Field `Notification`.`htmlBody` of type `String`)
  """
  htmlBody_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`resourceId` of type `String`
  """
  resourceId: String
  """
  ✨ `_expr` server value variant of `resourceId` (✨ Generated from Field `Notification`.`resourceId` of type `String`)
  """
  resourceId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`resourceType` of type `String`
  """
  resourceType: String
  """
  ✨ `_expr` server value variant of `resourceType` (✨ Generated from Field `Notification`.`resourceType` of type `String`)
  """
  resourceType_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Notification`.`title` of type `String!`
  """
  title: String
  """
  ✨ `_expr` server value variant of `title` (✨ Generated from Field `Notification`.`title` of type `String!`)
  """
  title_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Notification'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Notification_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Notification_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Notification_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Notification_Filter!]
  """
  ✨ Generated from Field `Notification`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Notification`.`memberId` of type `UUID!`
  """
  memberId: UUID_Filter
  """
  ✨ Generated from Field `Notification`.`member` of type `Member!`
  """
  member: Member_Filter
  """
  ✨ Generated from Field `Notification`.`actionMode` of type `String`
  """
  actionMode: String_Filter
  """
  ✨ Generated from Field `Notification`.`body` of type `String!`
  """
  body: String_Filter
  """
  ✨ Generated from Field `Notification`.`htmlBody` of type `String`
  """
  htmlBody: String_Filter
  """
  ✨ Generated from Field `Notification`.`resourceId` of type `String`
  """
  resourceId: String_Filter
  """
  ✨ Generated from Field `Notification`.`resourceType` of type `String`
  """
  resourceType: String_Filter
  """
  ✨ Generated from Field `Notification`.`title` of type `String!`
  """
  title: String_Filter
}
"""
✨ Generated first-row input type for table 'Notification'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Notification_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Notification_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Notification_Filter
}
"""
✨ Generated having input type for table 'Notification'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Notification_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Notification_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Notification_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Notification_Having!]
  """
  ✨ Generated from Field `Notification`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`actionMode_count` of type `Int!`
  """
  actionMode_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`body_count` of type `Int!`
  """
  body_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`htmlBody_count` of type `Int!`
  """
  htmlBody_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`memberId_count` of type `Int!`
  """
  memberId_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`resourceId_count` of type `Int!`
  """
  resourceId_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`resourceType_count` of type `Int!`
  """
  resourceType_count: Int_Filter
  """
  ✨ Generated from Field `Notification`.`title_count` of type `Int!`
  """
  title_count: Int_Filter
}
"""
✨ Generated key input type for table 'Notification'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Notification_Key {
  """
  ✨ Generated from Field `Notification`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Notification`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Notification'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Notification_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Notification_Filter
}
"""
✨ Generated order input type for table 'Notification'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Notification_Order {
  """
  ✨ Generated from Field `Notification`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Notification`.`memberId` of type `UUID!`
  """
  memberId: OrderDirection
  """
  ✨ Generated from Field `Notification`.`member` of type `Member!`
  """
  member: Member_Order
  """
  ✨ Generated from Field `Notification`.`actionMode` of type `String`
  """
  actionMode: OrderDirection
  """
  ✨ Generated from Field `Notification`.`body` of type `String!`
  """
  body: OrderDirection
  """
  ✨ Generated from Field `Notification`.`htmlBody` of type `String`
  """
  htmlBody: OrderDirection
  """
  ✨ Generated from Field `Notification`.`resourceId` of type `String`
  """
  resourceId: OrderDirection
  """
  ✨ Generated from Field `Notification`.`resourceType` of type `String`
  """
  resourceType: OrderDirection
  """
  ✨ Generated from Field `Notification`.`title` of type `String!`
  """
  title: OrderDirection
  """
  ✨ Generated from Field `Notification`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`actionMode_count` of type `Int!`
  """
  actionMode_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`body_count` of type `Int!`
  """
  body_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`htmlBody_count` of type `Int!`
  """
  htmlBody_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`memberId_count` of type `Int!`
  """
  memberId_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`resourceId_count` of type `Int!`
  """
  resourceId_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`resourceType_count` of type `Int!`
  """
  resourceType_count: OrderDirection
  """
  ✨ Generated from Field `Notification`.`title_count` of type `Int!`
  """
  title_count: OrderDirection
}
"""
✨ Generated data input type for table 'Proposal'. It includes all necessary fields for creating or upserting rows into table.
"""
input Proposal_Data {
  """
  ✨ Generated from Field `Proposal`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Proposal`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Proposal`.`hostId` of type `UUID!`
  """
  hostId: UUID
  """
  ✨ `_expr` server value variant of `hostId` (✨ Generated from Field `Proposal`.`hostId` of type `UUID!`)
  """
  hostId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Proposal`.`meetupId` of type `UUID!`
  """
  meetupId: UUID
  """
  ✨ `_expr` server value variant of `meetupId` (✨ Generated from Field `Proposal`.`meetupId` of type `UUID!`)
  """
  meetupId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Proposal`.`host` of type `Member!`
  """
  host: Member_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Proposal`.`meetup` of type `Meetup!`
  """
  meetup: Meetup_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Proposal`.`date` of type `Timestamp!`
  """
  date: Timestamp
  """
  ✨ `_expr` server value variant of `date` (✨ Generated from Field `Proposal`.`date` of type `Timestamp!`)
  """
  date_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `date` (✨ Generated from Field `Proposal`.`date` of type `Timestamp!`)
  """
  date_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `date` (✨ Generated from Field `Proposal`.`date` of type `Timestamp!`)
  """
  date_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Proposal`.`location` of type `String!`
  """
  location: String
  """
  ✨ `_expr` server value variant of `location` (✨ Generated from Field `Proposal`.`location` of type `String!`)
  """
  location_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Proposal`.`note` of type `String`
  """
  note: String
  """
  ✨ `_expr` server value variant of `note` (✨ Generated from Field `Proposal`.`note` of type `String`)
  """
  note_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Proposal`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `Proposal`.`status` of type `String!`)
  """
  status_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Proposal'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Proposal_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Proposal_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Proposal_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Proposal_Filter!]
  """
  ✨ Generated from Field `Proposal`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Proposal`.`hostId` of type `UUID!`
  """
  hostId: UUID_Filter
  """
  ✨ Generated from Field `Proposal`.`meetupId` of type `UUID!`
  """
  meetupId: UUID_Filter
  """
  ✨ Generated from Field `Proposal`.`host` of type `Member!`
  """
  host: Member_Filter
  """
  ✨ Generated from Field `Proposal`.`meetup` of type `Meetup!`
  """
  meetup: Meetup_Filter
  """
  ✨ Generated from Field `Proposal`.`date` of type `Timestamp!`
  """
  date: Timestamp_Filter
  """
  ✨ Generated from Field `Proposal`.`location` of type `String!`
  """
  location: String_Filter
  """
  ✨ Generated from Field `Proposal`.`note` of type `String`
  """
  note: String_Filter
  """
  ✨ Generated from Field `Proposal`.`status` of type `String!`
  """
  status: String_Filter
  """
  ✨ Generated from Field `Proposal`.`availabilities_on_proposal` of type `[Availability!]!`
  """
  availabilities_on_proposal: Availability_ListFilter
}
"""
✨ Generated first-row input type for table 'Proposal'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Proposal_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Proposal_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Proposal_Filter
}
"""
✨ Generated having input type for table 'Proposal'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Proposal_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Proposal_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Proposal_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Proposal_Having!]
  """
  ✨ Generated from Field `Proposal`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Proposal`.`date_count` of type `Int!`
  """
  date_count: Int_Filter
  """
  ✨ Generated from Field `Proposal`.`hostId_count` of type `Int!`
  """
  hostId_count: Int_Filter
  """
  ✨ Generated from Field `Proposal`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Proposal`.`location_count` of type `Int!`
  """
  location_count: Int_Filter
  """
  ✨ Generated from Field `Proposal`.`meetupId_count` of type `Int!`
  """
  meetupId_count: Int_Filter
  """
  ✨ Generated from Field `Proposal`.`note_count` of type `Int!`
  """
  note_count: Int_Filter
  """
  ✨ Generated from Field `Proposal`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `Proposal`.`date_min` of type `Timestamp`
  """
  date_min: Timestamp_Filter
  """
  ✨ Generated from Field `Proposal`.`date_max` of type `Timestamp`
  """
  date_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Proposal'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Proposal_Key {
  """
  ✨ Generated from Field `Proposal`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Proposal`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Proposal'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Proposal_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Proposal_Filter
}
"""
✨ Generated order input type for table 'Proposal'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Proposal_Order {
  """
  ✨ Generated from Field `Proposal`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`hostId` of type `UUID!`
  """
  hostId: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`meetupId` of type `UUID!`
  """
  meetupId: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`host` of type `Member!`
  """
  host: Member_Order
  """
  ✨ Generated from Field `Proposal`.`meetup` of type `Meetup!`
  """
  meetup: Meetup_Order
  """
  ✨ Generated from Field `Proposal`.`date` of type `Timestamp!`
  """
  date: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`location` of type `String!`
  """
  location: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`note` of type `String`
  """
  note: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`date_count` of type `Int!`
  """
  date_count: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`hostId_count` of type `Int!`
  """
  hostId_count: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`location_count` of type `Int!`
  """
  location_count: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`meetupId_count` of type `Int!`
  """
  meetupId_count: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`note_count` of type `Int!`
  """
  note_count: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`date_min` of type `Timestamp`
  """
  date_min: OrderDirection
  """
  ✨ Generated from Field `Proposal`.`date_max` of type `Timestamp`
  """
  date_max: OrderDirection
}
"""
✨ Generated data input type for table 'Tribe'. It includes all necessary fields for creating or upserting rows into table.
"""
input Tribe_Data {
  """
  ✨ Generated from Field `Tribe`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Tribe`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tribe`.`description` of type `String!`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Tribe`.`description` of type `String!`)
  """
  description_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tribe`.`iconType` of type `String`
  """
  iconType: String
  """
  ✨ `_expr` server value variant of `iconType` (✨ Generated from Field `Tribe`.`iconType` of type `String`)
  """
  iconType_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tribe`.`name` of type `String`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Tribe`.`name` of type `String`)
  """
  name_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Tribe'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Tribe_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Tribe_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Tribe_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Tribe_Filter!]
  """
  ✨ Generated from Field `Tribe`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Tribe`.`description` of type `String!`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Tribe`.`iconType` of type `String`
  """
  iconType: String_Filter
  """
  ✨ Generated from Field `Tribe`.`name` of type `String`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Tribe`.`meetups_on_tribe` of type `[Meetup!]!`
  """
  meetups_on_tribe: Meetup_ListFilter
  """
  ✨ Generated from Field `Tribe`.`tribeMembers_on_tribe` of type `[TribeMember!]!`
  """
  tribeMembers_on_tribe: TribeMember_ListFilter
}
"""
✨ Generated first-row input type for table 'Tribe'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Tribe_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Tribe_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Tribe_Filter
}
"""
✨ Generated having input type for table 'Tribe'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Tribe_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Tribe_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Tribe_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Tribe_Having!]
  """
  ✨ Generated from Field `Tribe`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Tribe`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Tribe`.`iconType_count` of type `Int!`
  """
  iconType_count: Int_Filter
  """
  ✨ Generated from Field `Tribe`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Tribe`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
}
"""
✨ Generated key input type for table 'Tribe'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Tribe_Key {
  """
  ✨ Generated from Field `Tribe`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Tribe`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Tribe'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Tribe_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Tribe_Filter
}
"""
✨ Generated order input type for table 'Tribe'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Tribe_Order {
  """
  ✨ Generated from Field `Tribe`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`description` of type `String!`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`iconType` of type `String`
  """
  iconType: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`name` of type `String`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`iconType_count` of type `Int!`
  """
  iconType_count: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
}
"""
✨ Generated data input type for table 'TribeMember'. It includes all necessary fields for creating or upserting rows into table.
"""
input TribeMember_Data {
  """
  ✨ Generated from Field `TribeMember`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `TribeMember`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `TribeMember`.`memberId` of type `UUID!`
  """
  memberId: UUID
  """
  ✨ `_expr` server value variant of `memberId` (✨ Generated from Field `TribeMember`.`memberId` of type `UUID!`)
  """
  memberId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `TribeMember`.`tribeId` of type `UUID!`
  """
  tribeId: UUID
  """
  ✨ `_expr` server value variant of `tribeId` (✨ Generated from Field `TribeMember`.`tribeId` of type `UUID!`)
  """
  tribeId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `TribeMember`.`member` of type `Member!`
  """
  member: Member_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `TribeMember`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Key @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'TribeMember'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input TribeMember_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [TribeMember_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: TribeMember_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [TribeMember_Filter!]
  """
  ✨ Generated from Field `TribeMember`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `TribeMember`.`memberId` of type `UUID!`
  """
  memberId: UUID_Filter
  """
  ✨ Generated from Field `TribeMember`.`tribeId` of type `UUID!`
  """
  tribeId: UUID_Filter
  """
  ✨ Generated from Field `TribeMember`.`member` of type `Member!`
  """
  member: Member_Filter
  """
  ✨ Generated from Field `TribeMember`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Filter
}
"""
✨ Generated first-row input type for table 'TribeMember'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input TribeMember_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [TribeMember_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: TribeMember_Filter
}
"""
✨ Generated having input type for table 'TribeMember'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input TribeMember_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [TribeMember_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: TribeMember_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [TribeMember_Having!]
  """
  ✨ Generated from Field `TribeMember`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `TribeMember`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `TribeMember`.`memberId_count` of type `Int!`
  """
  memberId_count: Int_Filter
  """
  ✨ Generated from Field `TribeMember`.`tribeId_count` of type `Int!`
  """
  tribeId_count: Int_Filter
}
"""
✨ Generated key input type for table 'TribeMember'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input TribeMember_Key {
  """
  ✨ Generated from Field `TribeMember`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `TribeMember`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'TribeMember'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input TribeMember_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: TribeMember_Filter
}
"""
✨ Generated order input type for table 'TribeMember'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input TribeMember_Order {
  """
  ✨ Generated from Field `TribeMember`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `TribeMember`.`memberId` of type `UUID!`
  """
  memberId: OrderDirection
  """
  ✨ Generated from Field `TribeMember`.`tribeId` of type `UUID!`
  """
  tribeId: OrderDirection
  """
  ✨ Generated from Field `TribeMember`.`member` of type `Member!`
  """
  member: Member_Order
  """
  ✨ Generated from Field `TribeMember`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Order
  """
  ✨ Generated from Field `TribeMember`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `TribeMember`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `TribeMember`.`memberId_count` of type `Int!`
  """
  memberId_count: OrderDirection
  """
  ✨ Generated from Field `TribeMember`.`tribeId_count` of type `Int!`
  """
  tribeId_count: OrderDirection
}
"""
✨ Generated data input type for table 'UserDevice'. It includes all necessary fields for creating or upserting rows into table.
"""
input UserDevice_Data {
  """
  ✨ Generated from Field `UserDevice`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `UserDevice`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserDevice`.`platform` of type `String!`
  """
  platform: String
  """
  ✨ `_expr` server value variant of `platform` (✨ Generated from Field `UserDevice`.`platform` of type `String!`)
  """
  platform_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserDevice`.`token` of type `String!`
  """
  token: String
  """
  ✨ `_expr` server value variant of `token` (✨ Generated from Field `UserDevice`.`token` of type `String!`)
  """
  token_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`
  """
  updatedAt: Date
  """
  ✨ `_date` server value variant of `updatedAt` (✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`)
  """
  updatedAt_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`)
  """
  updatedAt_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `updatedAt` (✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`)
  """
  updatedAt_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserDevice`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `UserDevice`.`userId` of type `String!`)
  """
  userId_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'UserDevice'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input UserDevice_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [UserDevice_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: UserDevice_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [UserDevice_Filter!]
  """
  ✨ Generated from Field `UserDevice`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `UserDevice`.`platform` of type `String!`
  """
  platform: String_Filter
  """
  ✨ Generated from Field `UserDevice`.`token` of type `String!`
  """
  token: String_Filter
  """
  ✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`
  """
  updatedAt: Date_Filter
  """
  ✨ Generated from Field `UserDevice`.`userId` of type `String!`
  """
  userId: String_Filter
}
"""
✨ Generated first-row input type for table 'UserDevice'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input UserDevice_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [UserDevice_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: UserDevice_Filter
}
"""
✨ Generated having input type for table 'UserDevice'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input UserDevice_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [UserDevice_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: UserDevice_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [UserDevice_Having!]
  """
  ✨ Generated from Field `UserDevice`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`platform_count` of type `Int!`
  """
  platform_count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`token_count` of type `Int!`
  """
  token_count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_min` of type `Date`
  """
  updatedAt_min: Date_Filter
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_max` of type `Date`
  """
  updatedAt_max: Date_Filter
}
"""
✨ Generated key input type for table 'UserDevice'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input UserDevice_Key {
  """
  ✨ Generated from Field `UserDevice`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `UserDevice`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'UserDevice'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input UserDevice_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: UserDevice_Filter
}
"""
✨ Generated order input type for table 'UserDevice'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input UserDevice_Order {
  """
  ✨ Generated from Field `UserDevice`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`platform` of type `String!`
  """
  platform: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`token` of type `String!`
  """
  token: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`userId` of type `String!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`platform_count` of type `Int!`
  """
  platform_count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`token_count` of type `Int!`
  """
  token_count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_min` of type `Date`
  """
  updatedAt_min: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_max` of type `Date`
  """
  updatedAt_max: OrderDirection
}
