"""
✨ `Account_KeyOutput` returns the primary key fields of table type `Account`.

It has the same format as `Account_Key`, but is only used as mutation return value.
"""
scalar Account_KeyOutput
"""
✨ `Availability_KeyOutput` returns the primary key fields of table type `Availability`.

It has the same format as `Availability_Key`, but is only used as mutation return value.
"""
scalar Availability_KeyOutput
"""
✨ `Fam_KeyOutput` returns the primary key fields of table type `Fam`.

It has the same format as `Fam_Key`, but is only used as mutation return value.
"""
scalar Fam_KeyOutput
"""
✨ `Meetup_KeyOutput` returns the primary key fields of table type `Meetup`.

It has the same format as `Meetup_Key`, but is only used as mutation return value.
"""
scalar Meetup_KeyOutput
"""
✨ `Tribe_KeyOutput` returns the primary key fields of table type `Tribe`.

It has the same format as `Tribe_Key`, but is only used as mutation return value.
"""
scalar Tribe_KeyOutput
"""
✨ `TribeFam_KeyOutput` returns the primary key fields of table type `TribeFam`.

It has the same format as `TribeFam_Key`, but is only used as mutation return value.
"""
scalar TribeFam_KeyOutput
"""
✨ `UserDevice_KeyOutput` returns the primary key fields of table type `UserDevice`.

It has the same format as `UserDevice_Key`, but is only used as mutation return value.
"""
scalar UserDevice_KeyOutput
"""
✨ Generated data input type for table 'Account'. It includes all necessary fields for creating or upserting rows into table.
"""
input Account_Data {
  """
  ✨ Generated from Field `Account`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Account`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Account`.`userId` of type `UUID!`
  """
  userId: UUID
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Account`.`userId` of type `UUID!`)
  """
  userId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Account`.`user` of type `Fam!`
  """
  user: Fam_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Account`.`network` of type `String!`
  """
  network: String
  """
  ✨ `_expr` server value variant of `network` (✨ Generated from Field `Account`.`network` of type `String!`)
  """
  network_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Account`.`networkUserId` of type `String`
  """
  networkUserId: String
  """
  ✨ `_expr` server value variant of `networkUserId` (✨ Generated from Field `Account`.`networkUserId` of type `String`)
  """
  networkUserId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Account`.`networkUsername` of type `String!`
  """
  networkUsername: String
  """
  ✨ `_expr` server value variant of `networkUsername` (✨ Generated from Field `Account`.`networkUsername` of type `String!`)
  """
  networkUsername_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Account`.`securityToken` of type `String`
  """
  securityToken: String
  """
  ✨ `_expr` server value variant of `securityToken` (✨ Generated from Field `Account`.`securityToken` of type `String`)
  """
  securityToken_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Account'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Account_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Account_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Account_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Account_Filter!]
  """
  ✨ Generated from Field `Account`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Account`.`userId` of type `UUID!`
  """
  userId: UUID_Filter
  """
  ✨ Generated from Field `Account`.`user` of type `Fam!`
  """
  user: Fam_Filter
  """
  ✨ Generated from Field `Account`.`network` of type `String!`
  """
  network: String_Filter
  """
  ✨ Generated from Field `Account`.`networkUserId` of type `String`
  """
  networkUserId: String_Filter
  """
  ✨ Generated from Field `Account`.`networkUsername` of type `String!`
  """
  networkUsername: String_Filter
  """
  ✨ Generated from Field `Account`.`securityToken` of type `String`
  """
  securityToken: String_Filter
}
"""
✨ Generated first-row input type for table 'Account'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Account_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Account_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Account_Filter
}
"""
✨ Generated having input type for table 'Account'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Account_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Account_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Account_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Account_Having!]
  """
  ✨ Generated from Field `Account`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Account`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Account`.`networkUserId_count` of type `Int!`
  """
  networkUserId_count: Int_Filter
  """
  ✨ Generated from Field `Account`.`networkUsername_count` of type `Int!`
  """
  networkUsername_count: Int_Filter
  """
  ✨ Generated from Field `Account`.`network_count` of type `Int!`
  """
  network_count: Int_Filter
  """
  ✨ Generated from Field `Account`.`securityToken_count` of type `Int!`
  """
  securityToken_count: Int_Filter
  """
  ✨ Generated from Field `Account`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
}
"""
✨ Generated key input type for table 'Account'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Account_Key {
  """
  ✨ Generated from Field `Account`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Account`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Account'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Account_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Account_Filter
}
"""
✨ Generated order input type for table 'Account'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Account_Order {
  """
  ✨ Generated from Field `Account`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Account`.`userId` of type `UUID!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `Account`.`user` of type `Fam!`
  """
  user: Fam_Order
  """
  ✨ Generated from Field `Account`.`network` of type `String!`
  """
  network: OrderDirection
  """
  ✨ Generated from Field `Account`.`networkUserId` of type `String`
  """
  networkUserId: OrderDirection
  """
  ✨ Generated from Field `Account`.`networkUsername` of type `String!`
  """
  networkUsername: OrderDirection
  """
  ✨ Generated from Field `Account`.`securityToken` of type `String`
  """
  securityToken: OrderDirection
  """
  ✨ Generated from Field `Account`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Account`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Account`.`networkUserId_count` of type `Int!`
  """
  networkUserId_count: OrderDirection
  """
  ✨ Generated from Field `Account`.`networkUsername_count` of type `Int!`
  """
  networkUsername_count: OrderDirection
  """
  ✨ Generated from Field `Account`.`network_count` of type `Int!`
  """
  network_count: OrderDirection
  """
  ✨ Generated from Field `Account`.`securityToken_count` of type `Int!`
  """
  securityToken_count: OrderDirection
  """
  ✨ Generated from Field `Account`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
}
"""
✨ Generated data input type for table 'Availability'. It includes all necessary fields for creating or upserting rows into table.
"""
input Availability_Data {
  """
  ✨ Generated from Field `Availability`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Availability`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`famId` of type `UUID!`
  """
  famId: UUID
  """
  ✨ `_expr` server value variant of `famId` (✨ Generated from Field `Availability`.`famId` of type `UUID!`)
  """
  famId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`meetupId` of type `UUID!`
  """
  meetupId: UUID
  """
  ✨ `_expr` server value variant of `meetupId` (✨ Generated from Field `Availability`.`meetupId` of type `UUID!`)
  """
  meetupId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`fam` of type `Fam!`
  """
  fam: Fam_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`meetup` of type `Meetup!`
  """
  meetup: Meetup_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`date` of type `Date!`
  """
  date: Date
  """
  ✨ `_date` server value variant of `date` (✨ Generated from Field `Availability`.`date` of type `Date!`)
  """
  date_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `date` (✨ Generated from Field `Availability`.`date` of type `Date!`)
  """
  date_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `date` (✨ Generated from Field `Availability`.`date` of type `Date!`)
  """
  date_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`location` of type `String!`
  """
  location: String
  """
  ✨ `_expr` server value variant of `location` (✨ Generated from Field `Availability`.`location` of type `String!`)
  """
  location_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Availability`.`note` of type `String`
  """
  note: String
  """
  ✨ `_expr` server value variant of `note` (✨ Generated from Field `Availability`.`note` of type `String`)
  """
  note_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Availability'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Availability_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Availability_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Availability_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Availability_Filter!]
  """
  ✨ Generated from Field `Availability`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Availability`.`famId` of type `UUID!`
  """
  famId: UUID_Filter
  """
  ✨ Generated from Field `Availability`.`meetupId` of type `UUID!`
  """
  meetupId: UUID_Filter
  """
  ✨ Generated from Field `Availability`.`fam` of type `Fam!`
  """
  fam: Fam_Filter
  """
  ✨ Generated from Field `Availability`.`meetup` of type `Meetup!`
  """
  meetup: Meetup_Filter
  """
  ✨ Generated from Field `Availability`.`date` of type `Date!`
  """
  date: Date_Filter
  """
  ✨ Generated from Field `Availability`.`location` of type `String!`
  """
  location: String_Filter
  """
  ✨ Generated from Field `Availability`.`note` of type `String`
  """
  note: String_Filter
}
"""
✨ Generated first-row input type for table 'Availability'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Availability_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Availability_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Availability_Filter
}
"""
✨ Generated having input type for table 'Availability'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Availability_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Availability_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Availability_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Availability_Having!]
  """
  ✨ Generated from Field `Availability`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`date_count` of type `Int!`
  """
  date_count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`famId_count` of type `Int!`
  """
  famId_count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`location_count` of type `Int!`
  """
  location_count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`meetupId_count` of type `Int!`
  """
  meetupId_count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`note_count` of type `Int!`
  """
  note_count: Int_Filter
  """
  ✨ Generated from Field `Availability`.`date_min` of type `Date`
  """
  date_min: Date_Filter
  """
  ✨ Generated from Field `Availability`.`date_max` of type `Date`
  """
  date_max: Date_Filter
}
"""
✨ Generated key input type for table 'Availability'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Availability_Key {
  """
  ✨ Generated from Field `Availability`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Availability`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Availability'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Availability_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Availability_Filter
}
"""
✨ Generated order input type for table 'Availability'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Availability_Order {
  """
  ✨ Generated from Field `Availability`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Availability`.`famId` of type `UUID!`
  """
  famId: OrderDirection
  """
  ✨ Generated from Field `Availability`.`meetupId` of type `UUID!`
  """
  meetupId: OrderDirection
  """
  ✨ Generated from Field `Availability`.`fam` of type `Fam!`
  """
  fam: Fam_Order
  """
  ✨ Generated from Field `Availability`.`meetup` of type `Meetup!`
  """
  meetup: Meetup_Order
  """
  ✨ Generated from Field `Availability`.`date` of type `Date!`
  """
  date: OrderDirection
  """
  ✨ Generated from Field `Availability`.`location` of type `String!`
  """
  location: OrderDirection
  """
  ✨ Generated from Field `Availability`.`note` of type `String`
  """
  note: OrderDirection
  """
  ✨ Generated from Field `Availability`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`date_count` of type `Int!`
  """
  date_count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`famId_count` of type `Int!`
  """
  famId_count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`location_count` of type `Int!`
  """
  location_count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`meetupId_count` of type `Int!`
  """
  meetupId_count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`note_count` of type `Int!`
  """
  note_count: OrderDirection
  """
  ✨ Generated from Field `Availability`.`date_min` of type `Date`
  """
  date_min: OrderDirection
  """
  ✨ Generated from Field `Availability`.`date_max` of type `Date`
  """
  date_max: OrderDirection
}
"""
✨ Generated data input type for table 'Fam'. It includes all necessary fields for creating or upserting rows into table.
"""
input Fam_Data {
  """
  ✨ Generated from Field `Fam`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Fam`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Fam`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `Fam`.`email` of type `String!`)
  """
  email_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Fam`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Fam`.`name` of type `String!`)
  """
  name_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Fam`.`userId` of type `String`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Fam`.`userId` of type `String`)
  """
  userId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Fam`.`accounts_on_user` of type `[Account!]!`
  """
  accounts_on_user: [Account_Data!]
  """
  ✨ Generated from Field `Fam`.`availabilities_on_fam` of type `[Availability!]!`
  """
  availabilities_on_fam: [Availability_Data!]
  """
  ✨ Generated from Field `Fam`.`meetups_on_host` of type `[Meetup!]!`
  """
  meetups_on_host: [Meetup_Data!]
  """
  ✨ Generated from Field `Fam`.`tribeFams_on_fam` of type `[TribeFam!]!`
  """
  tribeFams_on_fam: [TribeFam_Data!]
}
"""
✨ Generated filter input type for table 'Fam'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Fam_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Fam_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Fam_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Fam_Filter!]
  """
  ✨ Generated from Field `Fam`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Fam`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `Fam`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Fam`.`userId` of type `String`
  """
  userId: String_Filter
  """
  ✨ Generated from Field `Fam`.`accounts_on_user` of type `[Account!]!`
  """
  accounts_on_user: Account_ListFilter
  """
  ✨ Generated from Field `Fam`.`availabilities_on_fam` of type `[Availability!]!`
  """
  availabilities_on_fam: Availability_ListFilter
  """
  ✨ Generated from Field `Fam`.`meetups_on_host` of type `[Meetup!]!`
  """
  meetups_on_host: Meetup_ListFilter
  """
  ✨ Generated from Field `Fam`.`tribeFams_on_fam` of type `[TribeFam!]!`
  """
  tribeFams_on_fam: TribeFam_ListFilter
  """
  ✨ Generated from Field `Fam`.`tribes_via_TribeFam` of type `[Tribe!]!`
  """
  tribes_via_TribeFam: Tribe_ListFilter
}
"""
✨ Generated first-row input type for table 'Fam'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Fam_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Fam_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Fam_Filter
}
"""
✨ Generated having input type for table 'Fam'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Fam_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Fam_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Fam_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Fam_Having!]
  """
  ✨ Generated from Field `Fam`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Fam`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `Fam`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Fam`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Fam`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
}
"""
✨ Generated key input type for table 'Fam'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Fam_Key {
  """
  ✨ Generated from Field `Fam`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Fam`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Fam'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Fam_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Fam_Filter
}
"""
✨ Generated order input type for table 'Fam'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Fam_Order {
  """
  ✨ Generated from Field `Fam`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Fam`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `Fam`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Fam`.`userId` of type `String`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `Fam`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Fam`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `Fam`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Fam`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Fam`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
}
"""
✨ Generated data input type for table 'Meetup'. It includes all necessary fields for creating or upserting rows into table.
"""
input Meetup_Data {
  """
  ✨ Generated from Field `Meetup`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Meetup`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`hostId` of type `UUID!`
  """
  hostId: UUID
  """
  ✨ `_expr` server value variant of `hostId` (✨ Generated from Field `Meetup`.`hostId` of type `UUID!`)
  """
  hostId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`tribeId` of type `UUID!`
  """
  tribeId: UUID
  """
  ✨ `_expr` server value variant of `tribeId` (✨ Generated from Field `Meetup`.`tribeId` of type `UUID!`)
  """
  tribeId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`host` of type `Fam!`
  """
  host: Fam_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`details` of type `String`
  """
  details: String
  """
  ✨ `_expr` server value variant of `details` (✨ Generated from Field `Meetup`.`details` of type `String`)
  """
  details_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`note` of type `String`
  """
  note: String
  """
  ✨ `_expr` server value variant of `note` (✨ Generated from Field `Meetup`.`note` of type `String`)
  """
  note_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`title` of type `String`
  """
  title: String
  """
  ✨ `_expr` server value variant of `title` (✨ Generated from Field `Meetup`.`title` of type `String`)
  """
  title_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Meetup`.`availabilities_on_meetup` of type `[Availability!]!`
  """
  availabilities_on_meetup: [Availability_Data!]
}
"""
✨ Generated filter input type for table 'Meetup'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Meetup_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Meetup_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Meetup_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Meetup_Filter!]
  """
  ✨ Generated from Field `Meetup`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Meetup`.`hostId` of type `UUID!`
  """
  hostId: UUID_Filter
  """
  ✨ Generated from Field `Meetup`.`tribeId` of type `UUID!`
  """
  tribeId: UUID_Filter
  """
  ✨ Generated from Field `Meetup`.`host` of type `Fam!`
  """
  host: Fam_Filter
  """
  ✨ Generated from Field `Meetup`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Filter
  """
  ✨ Generated from Field `Meetup`.`details` of type `String`
  """
  details: String_Filter
  """
  ✨ Generated from Field `Meetup`.`note` of type `String`
  """
  note: String_Filter
  """
  ✨ Generated from Field `Meetup`.`title` of type `String`
  """
  title: String_Filter
  """
  ✨ Generated from Field `Meetup`.`availabilities_on_meetup` of type `[Availability!]!`
  """
  availabilities_on_meetup: Availability_ListFilter
}
"""
✨ Generated first-row input type for table 'Meetup'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Meetup_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Meetup_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Meetup_Filter
}
"""
✨ Generated having input type for table 'Meetup'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Meetup_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Meetup_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Meetup_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Meetup_Having!]
  """
  ✨ Generated from Field `Meetup`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`details_count` of type `Int!`
  """
  details_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`hostId_count` of type `Int!`
  """
  hostId_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`note_count` of type `Int!`
  """
  note_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`title_count` of type `Int!`
  """
  title_count: Int_Filter
  """
  ✨ Generated from Field `Meetup`.`tribeId_count` of type `Int!`
  """
  tribeId_count: Int_Filter
}
"""
✨ Generated key input type for table 'Meetup'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Meetup_Key {
  """
  ✨ Generated from Field `Meetup`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Meetup`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Meetup'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Meetup_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Meetup_Filter
}
"""
✨ Generated order input type for table 'Meetup'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Meetup_Order {
  """
  ✨ Generated from Field `Meetup`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`hostId` of type `UUID!`
  """
  hostId: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`tribeId` of type `UUID!`
  """
  tribeId: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`host` of type `Fam!`
  """
  host: Fam_Order
  """
  ✨ Generated from Field `Meetup`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Order
  """
  ✨ Generated from Field `Meetup`.`details` of type `String`
  """
  details: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`note` of type `String`
  """
  note: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`title` of type `String`
  """
  title: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`details_count` of type `Int!`
  """
  details_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`hostId_count` of type `Int!`
  """
  hostId_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`note_count` of type `Int!`
  """
  note_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`title_count` of type `Int!`
  """
  title_count: OrderDirection
  """
  ✨ Generated from Field `Meetup`.`tribeId_count` of type `Int!`
  """
  tribeId_count: OrderDirection
}
"""
✨ Generated data input type for table 'Tribe'. It includes all necessary fields for creating or upserting rows into table.
"""
input Tribe_Data {
  """
  ✨ Generated from Field `Tribe`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Tribe`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tribe`.`description` of type `String!`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Tribe`.`description` of type `String!`)
  """
  description_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tribe`.`name` of type `String`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Tribe`.`name` of type `String`)
  """
  name_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Tribe`.`meetups_on_tribe` of type `[Meetup!]!`
  """
  meetups_on_tribe: [Meetup_Data!]
  """
  ✨ Generated from Field `Tribe`.`tribeFams_on_tribe` of type `[TribeFam!]!`
  """
  tribeFams_on_tribe: [TribeFam_Data!]
}
"""
✨ Generated filter input type for table 'Tribe'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Tribe_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Tribe_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Tribe_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Tribe_Filter!]
  """
  ✨ Generated from Field `Tribe`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Tribe`.`description` of type `String!`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Tribe`.`name` of type `String`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Tribe`.`meetups_on_tribe` of type `[Meetup!]!`
  """
  meetups_on_tribe: Meetup_ListFilter
  """
  ✨ Generated from Field `Tribe`.`tribeFams_on_tribe` of type `[TribeFam!]!`
  """
  tribeFams_on_tribe: TribeFam_ListFilter
  """
  ✨ Generated from Field `Tribe`.`fams_via_TribeFam` of type `[Fam!]!`
  """
  fams_via_TribeFam: Fam_ListFilter
}
"""
✨ Generated first-row input type for table 'Tribe'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Tribe_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Tribe_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Tribe_Filter
}
"""
✨ Generated having input type for table 'Tribe'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Tribe_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Tribe_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Tribe_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Tribe_Having!]
  """
  ✨ Generated from Field `Tribe`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Tribe`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Tribe`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Tribe`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
}
"""
✨ Generated key input type for table 'Tribe'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Tribe_Key {
  """
  ✨ Generated from Field `Tribe`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Tribe`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Tribe'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Tribe_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Tribe_Filter
}
"""
✨ Generated order input type for table 'Tribe'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Tribe_Order {
  """
  ✨ Generated from Field `Tribe`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`description` of type `String!`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`name` of type `String`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Tribe`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
}
"""
✨ Generated data input type for table 'TribeFam'. It includes all necessary fields for creating or upserting rows into table.
"""
input TribeFam_Data {
  """
  ✨ Generated from Field `TribeFam`.`tribeId` of type `UUID!`
  """
  tribeId: UUID
  """
  ✨ `_expr` server value variant of `tribeId` (✨ Generated from Field `TribeFam`.`tribeId` of type `UUID!`)
  """
  tribeId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `TribeFam`.`famId` of type `UUID!`
  """
  famId: UUID
  """
  ✨ `_expr` server value variant of `famId` (✨ Generated from Field `TribeFam`.`famId` of type `UUID!`)
  """
  famId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `TribeFam`.`fam` of type `Fam!`
  """
  fam: Fam_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `TribeFam`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Key @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'TribeFam'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input TribeFam_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [TribeFam_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: TribeFam_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [TribeFam_Filter!]
  """
  ✨ Generated from Field `TribeFam`.`tribeId` of type `UUID!`
  """
  tribeId: UUID_Filter
  """
  ✨ Generated from Field `TribeFam`.`famId` of type `UUID!`
  """
  famId: UUID_Filter
  """
  ✨ Generated from Field `TribeFam`.`fam` of type `Fam!`
  """
  fam: Fam_Filter
  """
  ✨ Generated from Field `TribeFam`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Filter
}
"""
✨ Generated first-row input type for table 'TribeFam'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input TribeFam_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [TribeFam_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: TribeFam_Filter
}
"""
✨ Generated having input type for table 'TribeFam'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input TribeFam_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [TribeFam_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: TribeFam_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [TribeFam_Having!]
  """
  ✨ Generated from Field `TribeFam`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `TribeFam`.`famId_count` of type `Int!`
  """
  famId_count: Int_Filter
  """
  ✨ Generated from Field `TribeFam`.`tribeId_count` of type `Int!`
  """
  tribeId_count: Int_Filter
}
"""
✨ Generated key input type for table 'TribeFam'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input TribeFam_Key {
  """
  ✨ Generated from Field `TribeFam`.`tribeId` of type `UUID!`
  """
  tribeId: UUID
  """
  ✨ `_expr` server value variant of `tribeId` (✨ Generated from Field `TribeFam`.`tribeId` of type `UUID!`)
  """
  tribeId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `TribeFam`.`famId` of type `UUID!`
  """
  famId: UUID
  """
  ✨ `_expr` server value variant of `famId` (✨ Generated from Field `TribeFam`.`famId` of type `UUID!`)
  """
  famId_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'TribeFam'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input TribeFam_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: TribeFam_Filter
}
"""
✨ Generated order input type for table 'TribeFam'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input TribeFam_Order {
  """
  ✨ Generated from Field `TribeFam`.`tribeId` of type `UUID!`
  """
  tribeId: OrderDirection
  """
  ✨ Generated from Field `TribeFam`.`famId` of type `UUID!`
  """
  famId: OrderDirection
  """
  ✨ Generated from Field `TribeFam`.`fam` of type `Fam!`
  """
  fam: Fam_Order
  """
  ✨ Generated from Field `TribeFam`.`tribe` of type `Tribe!`
  """
  tribe: Tribe_Order
  """
  ✨ Generated from Field `TribeFam`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `TribeFam`.`famId_count` of type `Int!`
  """
  famId_count: OrderDirection
  """
  ✨ Generated from Field `TribeFam`.`tribeId_count` of type `Int!`
  """
  tribeId_count: OrderDirection
}
"""
✨ Generated data input type for table 'UserDevice'. It includes all necessary fields for creating or upserting rows into table.
"""
input UserDevice_Data {
  """
  ✨ Generated from Field `UserDevice`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `UserDevice`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserDevice`.`platform` of type `String!`
  """
  platform: String
  """
  ✨ `_expr` server value variant of `platform` (✨ Generated from Field `UserDevice`.`platform` of type `String!`)
  """
  platform_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserDevice`.`token` of type `String!`
  """
  token: String
  """
  ✨ `_expr` server value variant of `token` (✨ Generated from Field `UserDevice`.`token` of type `String!`)
  """
  token_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`
  """
  updatedAt: Date
  """
  ✨ `_date` server value variant of `updatedAt` (✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`)
  """
  updatedAt_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`)
  """
  updatedAt_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `updatedAt` (✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`)
  """
  updatedAt_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserDevice`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `UserDevice`.`userId` of type `String!`)
  """
  userId_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'UserDevice'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input UserDevice_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [UserDevice_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: UserDevice_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [UserDevice_Filter!]
  """
  ✨ Generated from Field `UserDevice`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `UserDevice`.`platform` of type `String!`
  """
  platform: String_Filter
  """
  ✨ Generated from Field `UserDevice`.`token` of type `String!`
  """
  token: String_Filter
  """
  ✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`
  """
  updatedAt: Date_Filter
  """
  ✨ Generated from Field `UserDevice`.`userId` of type `String!`
  """
  userId: String_Filter
}
"""
✨ Generated first-row input type for table 'UserDevice'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input UserDevice_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [UserDevice_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: UserDevice_Filter
}
"""
✨ Generated having input type for table 'UserDevice'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input UserDevice_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [UserDevice_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: UserDevice_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [UserDevice_Having!]
  """
  ✨ Generated from Field `UserDevice`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`platform_count` of type `Int!`
  """
  platform_count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`token_count` of type `Int!`
  """
  token_count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_min` of type `Date`
  """
  updatedAt_min: Date_Filter
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_max` of type `Date`
  """
  updatedAt_max: Date_Filter
}
"""
✨ Generated key input type for table 'UserDevice'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input UserDevice_Key {
  """
  ✨ Generated from Field `UserDevice`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `UserDevice`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'UserDevice'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input UserDevice_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: UserDevice_Filter
}
"""
✨ Generated order input type for table 'UserDevice'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input UserDevice_Order {
  """
  ✨ Generated from Field `UserDevice`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`platform` of type `String!`
  """
  platform: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`token` of type `String!`
  """
  token: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`updatedAt` of type `Date!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`userId` of type `String!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`platform_count` of type `Int!`
  """
  platform_count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`token_count` of type `Int!`
  """
  token_count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_min` of type `Date`
  """
  updatedAt_min: OrderDirection
  """
  ✨ Generated from Field `UserDevice`.`updatedAt_max` of type `Date`
  """
  updatedAt_max: OrderDirection
}
