extend type Mutation {
  """
  ✨ Insert a single `Account` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  account_insert(
    """
    Data object to insert into the table.
    """
    data: Account_Data!
  ): Account_KeyOutput! @fdc_generated(from: "Account", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Availability` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  availability_insert(
    """
    Data object to insert into the table.
    """
    data: Availability_Data!
  ): Availability_KeyOutput! @fdc_generated(from: "Availability", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Fam` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  fam_insert(
    """
    Data object to insert into the table.
    """
    data: Fam_Data!
  ): Fam_KeyOutput! @fdc_generated(from: "Fam", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Meetup` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  meetup_insert(
    """
    Data object to insert into the table.
    """
    data: Meetup_Data!
  ): Meetup_KeyOutput! @fdc_generated(from: "Meetup", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Tribe` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  tribe_insert(
    """
    Data object to insert into the table.
    """
    data: Tribe_Data!
  ): Tribe_KeyOutput! @fdc_generated(from: "Tribe", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `TribeFam` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  tribeFam_insert(
    """
    Data object to insert into the table.
    """
    data: TribeFam_Data!
  ): TribeFam_KeyOutput! @fdc_generated(from: "TribeFam", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserDevice` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userDevice_insert(
    """
    Data object to insert into the table.
    """
    data: UserDevice_Data!
  ): UserDevice_KeyOutput! @fdc_generated(from: "UserDevice", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Account` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  account_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Account_Data!]!
  ): [Account_KeyOutput!]! @fdc_generated(from: "Account", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Availability` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  availability_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Availability_Data!]!
  ): [Availability_KeyOutput!]! @fdc_generated(from: "Availability", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Fam` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  fam_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Fam_Data!]!
  ): [Fam_KeyOutput!]! @fdc_generated(from: "Fam", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Meetup` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  meetup_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Meetup_Data!]!
  ): [Meetup_KeyOutput!]! @fdc_generated(from: "Meetup", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Tribe` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  tribe_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Tribe_Data!]!
  ): [Tribe_KeyOutput!]! @fdc_generated(from: "Tribe", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `TribeFam` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  tribeFam_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TribeFam_Data!]!
  ): [TribeFam_KeyOutput!]! @fdc_generated(from: "TribeFam", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserDevice` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userDevice_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserDevice_Data!]!
  ): [UserDevice_KeyOutput!]! @fdc_generated(from: "UserDevice", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Account` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Account`.
  """
  account_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Account_Data!
  ): Account_KeyOutput! @fdc_generated(from: "Account", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Availability` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Availability`.
  """
  availability_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Availability_Data!
  ): Availability_KeyOutput! @fdc_generated(from: "Availability", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Fam` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Fam`.
  """
  fam_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Fam_Data!
  ): Fam_KeyOutput! @fdc_generated(from: "Fam", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Meetup` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Meetup`.
  """
  meetup_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Meetup_Data!
  ): Meetup_KeyOutput! @fdc_generated(from: "Meetup", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Tribe` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Tribe`.
  """
  tribe_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Tribe_Data!
  ): Tribe_KeyOutput! @fdc_generated(from: "Tribe", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `TribeFam` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TribeFam`.
  """
  tribeFam_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TribeFam_Data!
  ): TribeFam_KeyOutput! @fdc_generated(from: "TribeFam", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserDevice` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserDevice`.
  """
  userDevice_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserDevice_Data!
  ): UserDevice_KeyOutput! @fdc_generated(from: "UserDevice", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Account` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Account`.
  """
  account_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Account_Data!]!
  ): [Account_KeyOutput!]! @fdc_generated(from: "Account", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Availability` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Availability`.
  """
  availability_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Availability_Data!]!
  ): [Availability_KeyOutput!]! @fdc_generated(from: "Availability", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Fam` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Fam`.
  """
  fam_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Fam_Data!]!
  ): [Fam_KeyOutput!]! @fdc_generated(from: "Fam", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Meetup` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Meetup`.
  """
  meetup_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Meetup_Data!]!
  ): [Meetup_KeyOutput!]! @fdc_generated(from: "Meetup", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Tribe` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Tribe`.
  """
  tribe_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Tribe_Data!]!
  ): [Tribe_KeyOutput!]! @fdc_generated(from: "Tribe", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `TribeFam` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TribeFam`.
  """
  tribeFam_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TribeFam_Data!]!
  ): [TribeFam_KeyOutput!]! @fdc_generated(from: "TribeFam", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserDevice` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserDevice`.
  """
  userDevice_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserDevice_Data!]!
  ): [UserDevice_KeyOutput!]! @fdc_generated(from: "UserDevice", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Account` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Account` or `null` if not found.
  """
  account_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Account_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Account_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Account_Data!
  ): Account_KeyOutput @fdc_generated(from: "Account", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Availability` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Availability` or `null` if not found.
  """
  availability_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Availability_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Availability_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Availability_Data!
  ): Availability_KeyOutput @fdc_generated(from: "Availability", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Fam` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Fam` or `null` if not found.
  """
  fam_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Fam_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Fam_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Fam_Data!
  ): Fam_KeyOutput @fdc_generated(from: "Fam", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Meetup` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Meetup` or `null` if not found.
  """
  meetup_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Meetup_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Meetup_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Meetup_Data!
  ): Meetup_KeyOutput @fdc_generated(from: "Meetup", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Tribe` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Tribe` or `null` if not found.
  """
  tribe_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Tribe_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Tribe_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Tribe_Data!
  ): Tribe_KeyOutput @fdc_generated(from: "Tribe", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `TribeFam` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TribeFam` or `null` if not found.
  """
  tribeFam_update(
    """
    The key used to identify the object.
    """
    key: TribeFam_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TribeFam_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TribeFam_Data!
  ): TribeFam_KeyOutput @fdc_generated(from: "TribeFam", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserDevice` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserDevice` or `null` if not found.
  """
  userDevice_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserDevice_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserDevice_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserDevice_Data!
  ): UserDevice_KeyOutput @fdc_generated(from: "UserDevice", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Account` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  account_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Account_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Account_Data!
  ): Int! @fdc_generated(from: "Account", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Availability` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  availability_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Availability_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Availability_Data!
  ): Int! @fdc_generated(from: "Availability", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Fam` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  fam_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Fam_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Fam_Data!
  ): Int! @fdc_generated(from: "Fam", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Meetup` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  meetup_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Meetup_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Meetup_Data!
  ): Int! @fdc_generated(from: "Meetup", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Tribe` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  tribe_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Tribe_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Tribe_Data!
  ): Int! @fdc_generated(from: "Tribe", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `TribeFam` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  tribeFam_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TribeFam_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TribeFam_Data!
  ): Int! @fdc_generated(from: "TribeFam", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserDevice` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userDevice_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserDevice_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserDevice_Data!
  ): Int! @fdc_generated(from: "UserDevice", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Account` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  account_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Account_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Account_FirstRow
  ): Account_KeyOutput @fdc_generated(from: "Account", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Availability` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  availability_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Availability_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Availability_FirstRow
  ): Availability_KeyOutput @fdc_generated(from: "Availability", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Fam` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  fam_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Fam_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Fam_FirstRow
  ): Fam_KeyOutput @fdc_generated(from: "Fam", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Meetup` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  meetup_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Meetup_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Meetup_FirstRow
  ): Meetup_KeyOutput @fdc_generated(from: "Meetup", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Tribe` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  tribe_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Tribe_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Tribe_FirstRow
  ): Tribe_KeyOutput @fdc_generated(from: "Tribe", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `TribeFam` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  tribeFam_delete(
    """
    The key used to identify the object.
    """
    key: TribeFam_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TribeFam_FirstRow
  ): TribeFam_KeyOutput @fdc_generated(from: "TribeFam", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserDevice` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userDevice_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserDevice_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserDevice_FirstRow
  ): UserDevice_KeyOutput @fdc_generated(from: "UserDevice", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Account` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  account_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Account_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Account", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Availability` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  availability_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Availability_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Availability", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Fam` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  fam_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Fam_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Fam", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Meetup` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  meetup_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Meetup_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Meetup", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Tribe` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  tribe_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Tribe_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Tribe", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `TribeFam` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  tribeFam_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TribeFam_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TribeFam", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserDevice` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userDevice_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserDevice_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice", purpose: DELETE_MULTIPLE)
}
