extend type Mutation {
  """
  ✨ Insert a single `Availability` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  availability_insert(
    """
    Data object to insert into the table.
    """
    data: Availability_Data!
  ): Availability_KeyOutput! @fdc_generated(from: "Availability", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Chat` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  chat_insert(
    """
    Data object to insert into the table.
    """
    data: Chat_Data!
  ): Chat_KeyOutput! @fdc_generated(from: "Chat", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ChatMember` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  chatMember_insert(
    """
    Data object to insert into the table.
    """
    data: ChatMember_Data!
  ): ChatMember_KeyOutput! @fdc_generated(from: "ChatMember", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Meetup` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  meetup_insert(
    """
    Data object to insert into the table.
    """
    data: Meetup_Data!
  ): Meetup_KeyOutput! @fdc_generated(from: "Meetup", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Member` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  member_insert(
    """
    Data object to insert into the table.
    """
    data: Member_Data!
  ): Member_KeyOutput! @fdc_generated(from: "Member", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `MemberContact` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  memberContact_insert(
    """
    Data object to insert into the table.
    """
    data: MemberContact_Data!
  ): MemberContact_KeyOutput! @fdc_generated(from: "MemberContact", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Proposal` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  proposal_insert(
    """
    Data object to insert into the table.
    """
    data: Proposal_Data!
  ): Proposal_KeyOutput! @fdc_generated(from: "Proposal", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Tribe` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  tribe_insert(
    """
    Data object to insert into the table.
    """
    data: Tribe_Data!
  ): Tribe_KeyOutput! @fdc_generated(from: "Tribe", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `TribeMember` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  tribeMember_insert(
    """
    Data object to insert into the table.
    """
    data: TribeMember_Data!
  ): TribeMember_KeyOutput! @fdc_generated(from: "TribeMember", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserDevice` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userDevice_insert(
    """
    Data object to insert into the table.
    """
    data: UserDevice_Data!
  ): UserDevice_KeyOutput! @fdc_generated(from: "UserDevice", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Availability` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  availability_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Availability_Data!]!
  ): [Availability_KeyOutput!]! @fdc_generated(from: "Availability", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Chat` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  chat_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Chat_Data!]!
  ): [Chat_KeyOutput!]! @fdc_generated(from: "Chat", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ChatMember` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  chatMember_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ChatMember_Data!]!
  ): [ChatMember_KeyOutput!]! @fdc_generated(from: "ChatMember", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Meetup` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  meetup_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Meetup_Data!]!
  ): [Meetup_KeyOutput!]! @fdc_generated(from: "Meetup", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Member` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  member_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Member_Data!]!
  ): [Member_KeyOutput!]! @fdc_generated(from: "Member", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `MemberContact` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  memberContact_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [MemberContact_Data!]!
  ): [MemberContact_KeyOutput!]! @fdc_generated(from: "MemberContact", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Proposal` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  proposal_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Proposal_Data!]!
  ): [Proposal_KeyOutput!]! @fdc_generated(from: "Proposal", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Tribe` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  tribe_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Tribe_Data!]!
  ): [Tribe_KeyOutput!]! @fdc_generated(from: "Tribe", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `TribeMember` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  tribeMember_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TribeMember_Data!]!
  ): [TribeMember_KeyOutput!]! @fdc_generated(from: "TribeMember", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserDevice` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userDevice_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserDevice_Data!]!
  ): [UserDevice_KeyOutput!]! @fdc_generated(from: "UserDevice", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Availability` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Availability`.
  """
  availability_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Availability_Data!
  ): Availability_KeyOutput! @fdc_generated(from: "Availability", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Chat` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Chat`.
  """
  chat_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Chat_Data!
  ): Chat_KeyOutput! @fdc_generated(from: "Chat", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ChatMember` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ChatMember`.
  """
  chatMember_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ChatMember_Data!
  ): ChatMember_KeyOutput! @fdc_generated(from: "ChatMember", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Meetup` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Meetup`.
  """
  meetup_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Meetup_Data!
  ): Meetup_KeyOutput! @fdc_generated(from: "Meetup", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Member` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Member`.
  """
  member_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Member_Data!
  ): Member_KeyOutput! @fdc_generated(from: "Member", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `MemberContact` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MemberContact`.
  """
  memberContact_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: MemberContact_Data!
  ): MemberContact_KeyOutput! @fdc_generated(from: "MemberContact", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Proposal` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Proposal`.
  """
  proposal_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Proposal_Data!
  ): Proposal_KeyOutput! @fdc_generated(from: "Proposal", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Tribe` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Tribe`.
  """
  tribe_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Tribe_Data!
  ): Tribe_KeyOutput! @fdc_generated(from: "Tribe", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `TribeMember` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TribeMember`.
  """
  tribeMember_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TribeMember_Data!
  ): TribeMember_KeyOutput! @fdc_generated(from: "TribeMember", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserDevice` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserDevice`.
  """
  userDevice_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserDevice_Data!
  ): UserDevice_KeyOutput! @fdc_generated(from: "UserDevice", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Availability` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Availability`.
  """
  availability_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Availability_Data!]!
  ): [Availability_KeyOutput!]! @fdc_generated(from: "Availability", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Chat` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Chat`.
  """
  chat_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Chat_Data!]!
  ): [Chat_KeyOutput!]! @fdc_generated(from: "Chat", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ChatMember` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ChatMember`.
  """
  chatMember_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ChatMember_Data!]!
  ): [ChatMember_KeyOutput!]! @fdc_generated(from: "ChatMember", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Meetup` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Meetup`.
  """
  meetup_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Meetup_Data!]!
  ): [Meetup_KeyOutput!]! @fdc_generated(from: "Meetup", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Member` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Member`.
  """
  member_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Member_Data!]!
  ): [Member_KeyOutput!]! @fdc_generated(from: "Member", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `MemberContact` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MemberContact`.
  """
  memberContact_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [MemberContact_Data!]!
  ): [MemberContact_KeyOutput!]! @fdc_generated(from: "MemberContact", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Proposal` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Proposal`.
  """
  proposal_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Proposal_Data!]!
  ): [Proposal_KeyOutput!]! @fdc_generated(from: "Proposal", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Tribe` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Tribe`.
  """
  tribe_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Tribe_Data!]!
  ): [Tribe_KeyOutput!]! @fdc_generated(from: "Tribe", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `TribeMember` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TribeMember`.
  """
  tribeMember_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TribeMember_Data!]!
  ): [TribeMember_KeyOutput!]! @fdc_generated(from: "TribeMember", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserDevice` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserDevice`.
  """
  userDevice_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserDevice_Data!]!
  ): [UserDevice_KeyOutput!]! @fdc_generated(from: "UserDevice", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Availability` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Availability` or `null` if not found.
  """
  availability_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Availability_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Availability_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Availability_Data!
  ): Availability_KeyOutput @fdc_generated(from: "Availability", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Chat` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Chat` or `null` if not found.
  """
  chat_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Chat_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Chat_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Chat_Data!
  ): Chat_KeyOutput @fdc_generated(from: "Chat", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ChatMember` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ChatMember` or `null` if not found.
  """
  chatMember_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ChatMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ChatMember_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ChatMember_Data!
  ): ChatMember_KeyOutput @fdc_generated(from: "ChatMember", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Meetup` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Meetup` or `null` if not found.
  """
  meetup_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Meetup_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Meetup_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Meetup_Data!
  ): Meetup_KeyOutput @fdc_generated(from: "Meetup", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Member` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Member` or `null` if not found.
  """
  member_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Member_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Member_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Member_Data!
  ): Member_KeyOutput @fdc_generated(from: "Member", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `MemberContact` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `MemberContact` or `null` if not found.
  """
  memberContact_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MemberContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MemberContact_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: MemberContact_Data!
  ): MemberContact_KeyOutput @fdc_generated(from: "MemberContact", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Proposal` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Proposal` or `null` if not found.
  """
  proposal_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Proposal_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Proposal_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Proposal_Data!
  ): Proposal_KeyOutput @fdc_generated(from: "Proposal", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Tribe` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Tribe` or `null` if not found.
  """
  tribe_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Tribe_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Tribe_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Tribe_Data!
  ): Tribe_KeyOutput @fdc_generated(from: "Tribe", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `TribeMember` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TribeMember` or `null` if not found.
  """
  tribeMember_update(
    """
    The key used to identify the object.
    """
    key: TribeMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TribeMember_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TribeMember_Data!
  ): TribeMember_KeyOutput @fdc_generated(from: "TribeMember", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserDevice` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserDevice` or `null` if not found.
  """
  userDevice_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserDevice_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserDevice_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserDevice_Data!
  ): UserDevice_KeyOutput @fdc_generated(from: "UserDevice", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Availability` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  availability_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Availability_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Availability_Data!
  ): Int! @fdc_generated(from: "Availability", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Chat` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  chat_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Chat_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Chat_Data!
  ): Int! @fdc_generated(from: "Chat", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ChatMember` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  chatMember_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ChatMember_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ChatMember_Data!
  ): Int! @fdc_generated(from: "ChatMember", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Meetup` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  meetup_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Meetup_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Meetup_Data!
  ): Int! @fdc_generated(from: "Meetup", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Member` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  member_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Member_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Member_Data!
  ): Int! @fdc_generated(from: "Member", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `MemberContact` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  memberContact_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: MemberContact_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: MemberContact_Data!
  ): Int! @fdc_generated(from: "MemberContact", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Proposal` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  proposal_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Proposal_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Proposal_Data!
  ): Int! @fdc_generated(from: "Proposal", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Tribe` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  tribe_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Tribe_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Tribe_Data!
  ): Int! @fdc_generated(from: "Tribe", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `TribeMember` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  tribeMember_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TribeMember_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TribeMember_Data!
  ): Int! @fdc_generated(from: "TribeMember", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserDevice` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userDevice_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserDevice_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserDevice_Data!
  ): Int! @fdc_generated(from: "UserDevice", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Availability` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  availability_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Availability_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Availability_FirstRow
  ): Availability_KeyOutput @fdc_generated(from: "Availability", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Chat` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  chat_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Chat_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Chat_FirstRow
  ): Chat_KeyOutput @fdc_generated(from: "Chat", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ChatMember` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  chatMember_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ChatMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ChatMember_FirstRow
  ): ChatMember_KeyOutput @fdc_generated(from: "ChatMember", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Meetup` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  meetup_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Meetup_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Meetup_FirstRow
  ): Meetup_KeyOutput @fdc_generated(from: "Meetup", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Member` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  member_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Member_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Member_FirstRow
  ): Member_KeyOutput @fdc_generated(from: "Member", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `MemberContact` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  memberContact_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MemberContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MemberContact_FirstRow
  ): MemberContact_KeyOutput @fdc_generated(from: "MemberContact", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Proposal` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  proposal_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Proposal_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Proposal_FirstRow
  ): Proposal_KeyOutput @fdc_generated(from: "Proposal", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Tribe` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  tribe_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Tribe_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Tribe_FirstRow
  ): Tribe_KeyOutput @fdc_generated(from: "Tribe", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `TribeMember` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  tribeMember_delete(
    """
    The key used to identify the object.
    """
    key: TribeMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TribeMember_FirstRow
  ): TribeMember_KeyOutput @fdc_generated(from: "TribeMember", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserDevice` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userDevice_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserDevice_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserDevice_FirstRow
  ): UserDevice_KeyOutput @fdc_generated(from: "UserDevice", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Availability` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  availability_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Availability_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Availability", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Chat` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  chat_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Chat_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Chat", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ChatMember` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  chatMember_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ChatMember_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ChatMember", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Meetup` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  meetup_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Meetup_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Meetup", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Member` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  member_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Member_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Member", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `MemberContact` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  memberContact_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: MemberContact_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "MemberContact", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Proposal` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  proposal_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Proposal_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Proposal", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Tribe` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  tribe_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Tribe_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Tribe", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `TribeMember` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  tribeMember_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TribeMember_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TribeMember", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserDevice` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userDevice_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserDevice_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice", purpose: DELETE_MULTIPLE)
}
