extend type Query {
  """
  ✨ Look up a single `Account` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  account(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Account_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Account_FirstRow
  ): Account @fdc_generated(from: "Account", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Availability` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  availability(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Availability_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Availability_FirstRow
  ): Availability @fdc_generated(from: "Availability", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Fam` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  fam(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Fam_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Fam_FirstRow
  ): Fam @fdc_generated(from: "Fam", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Meetup` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  meetup(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Meetup_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Meetup_FirstRow
  ): Meetup @fdc_generated(from: "Meetup", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Tribe` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  tribe(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Tribe_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Tribe_FirstRow
  ): Tribe @fdc_generated(from: "Tribe", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TribeFam` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  tribeFam(
    """
    The key used to identify the object.
    """
    key: TribeFam_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TribeFam_FirstRow
  ): TribeFam @fdc_generated(from: "TribeFam", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserDevice` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userDevice(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserDevice_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserDevice_FirstRow
  ): UserDevice @fdc_generated(from: "UserDevice", purpose: QUERY_SINGLE)
  """
  ✨ List `Account` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  accounts(
    """
    Filter condition to narrow down the query results.
    """
    where: Account_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Account_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Account_Having
  ): [Account!]! @fdc_generated(from: "Account", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Availability` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  availabilities(
    """
    Filter condition to narrow down the query results.
    """
    where: Availability_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Availability_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Availability_Having
  ): [Availability!]! @fdc_generated(from: "Availability", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Fam` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  fams(
    """
    Filter condition to narrow down the query results.
    """
    where: Fam_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Fam_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Fam_Having
  ): [Fam!]! @fdc_generated(from: "Fam", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Meetup` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  meetups(
    """
    Filter condition to narrow down the query results.
    """
    where: Meetup_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Meetup_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Meetup_Having
  ): [Meetup!]! @fdc_generated(from: "Meetup", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Tribe` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tribes(
    """
    Filter condition to narrow down the query results.
    """
    where: Tribe_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Tribe_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Tribe_Having
  ): [Tribe!]! @fdc_generated(from: "Tribe", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TribeFam` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tribeFams(
    """
    Filter condition to narrow down the query results.
    """
    where: TribeFam_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TribeFam_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TribeFam_Having
  ): [TribeFam!]! @fdc_generated(from: "TribeFam", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserDevice` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userDevices(
    """
    Filter condition to narrow down the query results.
    """
    where: UserDevice_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserDevice_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserDevice_Having
  ): [UserDevice!]! @fdc_generated(from: "UserDevice", purpose: QUERY_MULTIPLE)
}
