extend type Query {
  """
  ✨ Look up a single `Availability` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  availability(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Availability_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Availability_FirstRow
  ): Availability @fdc_generated(from: "Availability", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Chat` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  chat(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Chat_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Chat_FirstRow
  ): Chat @fdc_generated(from: "Chat", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ChatMember` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  chatMember(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ChatMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ChatMember_FirstRow
  ): ChatMember @fdc_generated(from: "ChatMember", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Meetup` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  meetup(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Meetup_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Meetup_FirstRow
  ): Meetup @fdc_generated(from: "Meetup", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Member` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  member(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Member_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Member_FirstRow
  ): Member @fdc_generated(from: "Member", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MemberContact` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  memberContact(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MemberContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MemberContact_FirstRow
  ): MemberContact @fdc_generated(from: "MemberContact", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Proposal` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  proposal(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Proposal_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Proposal_FirstRow
  ): Proposal @fdc_generated(from: "Proposal", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Tribe` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  tribe(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Tribe_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Tribe_FirstRow
  ): Tribe @fdc_generated(from: "Tribe", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TribeMember` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  tribeMember(
    """
    The key used to identify the object.
    """
    key: TribeMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TribeMember_FirstRow
  ): TribeMember @fdc_generated(from: "TribeMember", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserDevice` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userDevice(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserDevice_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserDevice_FirstRow
  ): UserDevice @fdc_generated(from: "UserDevice", purpose: QUERY_SINGLE)
  """
  ✨ List `Availability` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  availabilities(
    """
    Filter condition to narrow down the query results.
    """
    where: Availability_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Availability_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Availability_Having
  ): [Availability!]! @fdc_generated(from: "Availability", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Chat` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  chats(
    """
    Filter condition to narrow down the query results.
    """
    where: Chat_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Chat_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Chat_Having
  ): [Chat!]! @fdc_generated(from: "Chat", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ChatMember` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  chatMembers(
    """
    Filter condition to narrow down the query results.
    """
    where: ChatMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ChatMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ChatMember_Having
  ): [ChatMember!]! @fdc_generated(from: "ChatMember", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Meetup` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  meetups(
    """
    Filter condition to narrow down the query results.
    """
    where: Meetup_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Meetup_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Meetup_Having
  ): [Meetup!]! @fdc_generated(from: "Meetup", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Member` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  members(
    """
    Filter condition to narrow down the query results.
    """
    where: Member_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Member_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Member_Having
  ): [Member!]! @fdc_generated(from: "Member", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MemberContact` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  memberContacts(
    """
    Filter condition to narrow down the query results.
    """
    where: MemberContact_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MemberContact_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MemberContact_Having
  ): [MemberContact!]! @fdc_generated(from: "MemberContact", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Proposal` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  proposals(
    """
    Filter condition to narrow down the query results.
    """
    where: Proposal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Proposal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Proposal_Having
  ): [Proposal!]! @fdc_generated(from: "Proposal", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Tribe` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tribes(
    """
    Filter condition to narrow down the query results.
    """
    where: Tribe_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Tribe_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Tribe_Having
  ): [Tribe!]! @fdc_generated(from: "Tribe", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TribeMember` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tribeMembers(
    """
    Filter condition to narrow down the query results.
    """
    where: TribeMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TribeMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TribeMember_Having
  ): [TribeMember!]! @fdc_generated(from: "TribeMember", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserDevice` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userDevices(
    """
    Filter condition to narrow down the query results.
    """
    where: UserDevice_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserDevice_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserDevice_Having
  ): [UserDevice!]! @fdc_generated(from: "UserDevice", purpose: QUERY_MULTIPLE)
}
