extend type Account {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Account", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Account` table.
  """
  _count: Int! @fdc_generated(from: "Account.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `networkUserId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  networkUserId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.networkUserId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `networkUsername` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  networkUsername_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.networkUsername", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `network` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  network_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.network", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `securityToken` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  securityToken_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.securityToken", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.userId", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Account.id", purpose: ENTITY_ID)
}
extend type Availability {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Availability", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Availability` table.
  """
  _count: Int! @fdc_generated(from: "Availability.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `date` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  date_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.date", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `famId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  famId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.famId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `location` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  location_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.location", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `meetupId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  meetupId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.meetupId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `note` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  note_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.note", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `date` field in the `Availability` table.
  """
  date_min: Date @fdc_generated(from: "Availability.date", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `date` field in the `Availability` table.
  """
  date_max: Date @fdc_generated(from: "Availability.date", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Availability.id", purpose: ENTITY_ID)
}
extend type Fam {
  """
  ✨ List `Account` objects in a one-to-many relationship (where `Account`.`user` is this object).
  """
  accounts_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Account_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Account_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Account_Having
  ): [Account!]! @fdc_generated(from: "Account.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Availability` objects in a one-to-many relationship (where `Availability`.`fam` is this object).
  """
  availabilities_on_fam(
    """
    Filter condition to narrow down the query results.
    """
    where: Availability_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Availability_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Availability_Having
  ): [Availability!]! @fdc_generated(from: "Availability.fam", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Meetup` objects in a one-to-many relationship (where `Meetup`.`host` is this object).
  """
  meetups_on_host(
    """
    Filter condition to narrow down the query results.
    """
    where: Meetup_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Meetup_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Meetup_Having
  ): [Meetup!]! @fdc_generated(from: "Meetup.host", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `TribeFam` objects in a one-to-many relationship (where `TribeFam`.`fam` is this object).
  """
  tribeFams_on_fam(
    """
    Filter condition to narrow down the query results.
    """
    where: TribeFam_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TribeFam_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TribeFam_Having
  ): [TribeFam!]! @fdc_generated(from: "TribeFam.fam", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Tribe` objects using `TribeFam` as the join table (a `TribeFam` object exists where its `fam` is this and its `tribe` is that).
  """
  tribes_via_TribeFam(
    """
    Filter condition to narrow down the query results.
    """
    where: TribeFam_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TribeFam_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TribeFam_Having
  ): [Tribe!]! @fdc_generated(from: "TribeFam", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Fam", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Fam` table.
  """
  _count: Int! @fdc_generated(from: "Fam.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Fam` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Fam.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Fam` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Fam.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Fam` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Fam.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Fam` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Fam.userId", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Fam.id", purpose: ENTITY_ID)
}
extend type Meetup {
  """
  ✨ List `Availability` objects in a one-to-many relationship (where `Availability`.`meetup` is this object).
  """
  availabilities_on_meetup(
    """
    Filter condition to narrow down the query results.
    """
    where: Availability_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Availability_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Availability_Having
  ): [Availability!]! @fdc_generated(from: "Availability.meetup", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Meetup", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Meetup` table.
  """
  _count: Int! @fdc_generated(from: "Meetup.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `details` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  details_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.details", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `hostId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  hostId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.hostId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `note` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  note_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.note", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `tribeId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tribeId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.tribeId", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Meetup.id", purpose: ENTITY_ID)
}
extend type Tribe {
  """
  ✨ List `Meetup` objects in a one-to-many relationship (where `Meetup`.`tribe` is this object).
  """
  meetups_on_tribe(
    """
    Filter condition to narrow down the query results.
    """
    where: Meetup_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Meetup_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Meetup_Having
  ): [Meetup!]! @fdc_generated(from: "Meetup.tribe", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `TribeFam` objects in a one-to-many relationship (where `TribeFam`.`tribe` is this object).
  """
  tribeFams_on_tribe(
    """
    Filter condition to narrow down the query results.
    """
    where: TribeFam_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TribeFam_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TribeFam_Having
  ): [TribeFam!]! @fdc_generated(from: "TribeFam.tribe", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Fam` objects using `TribeFam` as the join table (a `TribeFam` object exists where its `tribe` is this and its `fam` is that).
  """
  fams_via_TribeFam(
    """
    Filter condition to narrow down the query results.
    """
    where: TribeFam_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TribeFam_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TribeFam_Having
  ): [Fam!]! @fdc_generated(from: "TribeFam", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Tribe", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Tribe` table.
  """
  _count: Int! @fdc_generated(from: "Tribe.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tribe` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tribe.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tribe` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tribe.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tribe` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tribe.name", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Tribe.id", purpose: ENTITY_ID)
}
extend type TribeFam {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "TribeFam", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `TribeFam` table.
  """
  _count: Int! @fdc_generated(from: "TribeFam.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TribeFam` table where the `famId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  famId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TribeFam.famId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TribeFam` table where the `tribeId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tribeId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TribeFam.tribeId", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "TribeFam.tribeId,famId", purpose: ENTITY_ID)
}
extend type UserDevice {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "UserDevice", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `UserDevice` table.
  """
  _count: Int! @fdc_generated(from: "UserDevice.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserDevice` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserDevice` table where the `platform` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  platform_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice.platform", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserDevice` table where the `token` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  token_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice.token", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserDevice` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserDevice` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `updatedAt` field in the `UserDevice` table.
  """
  updatedAt_min: Date @fdc_generated(from: "UserDevice.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `updatedAt` field in the `UserDevice` table.
  """
  updatedAt_max: Date @fdc_generated(from: "UserDevice.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "UserDevice.id", purpose: ENTITY_ID)
}
