extend type Availability {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Availability", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Availability` table.
  """
  _count: Int! @fdc_generated(from: "Availability.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `memberId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  memberId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.memberId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `note` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  note_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.note", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `proposalId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  proposalId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.proposalId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Availability` table where the `vote` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  vote_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Availability.vote", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Availability.id", purpose: ENTITY_ID)
}
extend type Chat {
  """
  ✨ List `ChatMember` objects in a one-to-many relationship (where `ChatMember`.`chat` is this object).
  """
  chatMembers_on_chat(
    """
    Filter condition to narrow down the query results.
    """
    where: ChatMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ChatMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ChatMember_Having
  ): [ChatMember!]! @fdc_generated(from: "ChatMember.chat", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Chat", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Chat` table.
  """
  _count: Int! @fdc_generated(from: "Chat.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Chat` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Chat.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Chat` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Chat.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Chat` table where the `url` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  url_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Chat.url", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Chat.id", purpose: ENTITY_ID)
}
extend type ChatMember {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "ChatMember", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `ChatMember` table.
  """
  _count: Int! @fdc_generated(from: "ChatMember.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ChatMember` table where the `chatId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  chatId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ChatMember.chatId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ChatMember` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ChatMember.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ChatMember` table where the `memberId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  memberId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ChatMember.memberId", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "ChatMember.id", purpose: ENTITY_ID)
}
extend type Meetup {
  """
  ✨ List `Proposal` objects in a one-to-many relationship (where `Proposal`.`meetup` is this object).
  """
  proposals_on_meetup(
    """
    Filter condition to narrow down the query results.
    """
    where: Proposal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Proposal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Proposal_Having
  ): [Proposal!]! @fdc_generated(from: "Proposal.meetup", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Meetup", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Meetup` table.
  """
  _count: Int! @fdc_generated(from: "Meetup.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `creatorId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  creatorId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.creatorId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `daysToDecide` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  daysToDecide_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.daysToDecide", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `decisionMethod` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  decisionMethod_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.decisionMethod", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `details` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  details_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.details", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `recursEveryDays` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  recursEveryDays_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.recursEveryDays", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Meetup` table where the `tribeId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tribeId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Meetup.tribeId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `daysToDecide` field in the `Meetup` table.
  """
  daysToDecide_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Meetup.daysToDecide", purpose: QUERY_SUM)
  """
  ✨ Sum the `recursEveryDays` field in the `Meetup` table.
  """
  recursEveryDays_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Meetup.recursEveryDays", purpose: QUERY_SUM)
  """
  ✨ Average the `daysToDecide` field in the `Meetup` table.
  """
  daysToDecide_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Meetup.daysToDecide", purpose: QUERY_AVG)
  """
  ✨ Average the `recursEveryDays` field in the `Meetup` table.
  """
  recursEveryDays_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Meetup.recursEveryDays", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Meetup` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Meetup.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `daysToDecide` field in the `Meetup` table.
  """
  daysToDecide_min: Int @fdc_generated(from: "Meetup.daysToDecide", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `recursEveryDays` field in the `Meetup` table.
  """
  recursEveryDays_min: Int @fdc_generated(from: "Meetup.recursEveryDays", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Meetup` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Meetup.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `daysToDecide` field in the `Meetup` table.
  """
  daysToDecide_max: Int @fdc_generated(from: "Meetup.daysToDecide", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `recursEveryDays` field in the `Meetup` table.
  """
  recursEveryDays_max: Int @fdc_generated(from: "Meetup.recursEveryDays", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Meetup.id", purpose: ENTITY_ID)
}
extend type Member {
  """
  ✨ List `Availability` objects in a one-to-many relationship (where `Availability`.`member` is this object).
  """
  availabilities_on_member(
    """
    Filter condition to narrow down the query results.
    """
    where: Availability_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Availability_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Availability_Having
  ): [Availability!]! @fdc_generated(from: "Availability.member", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `ChatMember` objects in a one-to-many relationship (where `ChatMember`.`member` is this object).
  """
  chatMembers_on_member(
    """
    Filter condition to narrow down the query results.
    """
    where: ChatMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ChatMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ChatMember_Having
  ): [ChatMember!]! @fdc_generated(from: "ChatMember.member", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Meetup` objects in a one-to-many relationship (where `Meetup`.`creator` is this object).
  """
  meetups_on_creator(
    """
    Filter condition to narrow down the query results.
    """
    where: Meetup_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Meetup_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Meetup_Having
  ): [Meetup!]! @fdc_generated(from: "Meetup.creator", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `MemberContact` objects in a one-to-many relationship (where `MemberContact`.`source` is this object).
  """
  memberContacts_on_source(
    """
    Filter condition to narrow down the query results.
    """
    where: MemberContact_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MemberContact_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MemberContact_Having
  ): [MemberContact!]! @fdc_generated(from: "MemberContact.source", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `MemberContact` objects in a one-to-many relationship (where `MemberContact`.`subject` is this object).
  """
  memberContacts_on_subject(
    """
    Filter condition to narrow down the query results.
    """
    where: MemberContact_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MemberContact_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MemberContact_Having
  ): [MemberContact!]! @fdc_generated(from: "MemberContact.subject", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Proposal` objects in a one-to-many relationship (where `Proposal`.`host` is this object).
  """
  proposals_on_host(
    """
    Filter condition to narrow down the query results.
    """
    where: Proposal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Proposal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Proposal_Having
  ): [Proposal!]! @fdc_generated(from: "Proposal.host", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `TribeMember` objects in a one-to-many relationship (where `TribeMember`.`member` is this object).
  """
  tribeMembers_on_member(
    """
    Filter condition to narrow down the query results.
    """
    where: TribeMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TribeMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TribeMember_Having
  ): [TribeMember!]! @fdc_generated(from: "TribeMember.member", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Tribe` objects using `TribeMember` as the join table (a `TribeMember` object exists where its `member` is this and its `tribe` is that).
  """
  tribes_via_TribeMember(
    """
    Filter condition to narrow down the query results.
    """
    where: TribeMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TribeMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TribeMember_Having
  ): [Tribe!]! @fdc_generated(from: "TribeMember", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Member", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Member` table.
  """
  _count: Int! @fdc_generated(from: "Member.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Member` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Member.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Member` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Member.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Member` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Member.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Member` table where the `phone` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phone_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Member.phone", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Member` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Member.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Member` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Member.userId", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Member.id", purpose: ENTITY_ID)
}
extend type MemberContact {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "MemberContact", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `MemberContact` table.
  """
  _count: Int! @fdc_generated(from: "MemberContact.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MemberContact` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MemberContact.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MemberContact` table where the `sourceId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  sourceId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MemberContact.sourceId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MemberContact` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MemberContact.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MemberContact` table where the `subjectId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  subjectId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MemberContact.subjectId", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "MemberContact.id", purpose: ENTITY_ID)
}
extend type Proposal {
  """
  ✨ List `Availability` objects in a one-to-many relationship (where `Availability`.`proposal` is this object).
  """
  availabilities_on_proposal(
    """
    Filter condition to narrow down the query results.
    """
    where: Availability_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Availability_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Availability_Having
  ): [Availability!]! @fdc_generated(from: "Availability.proposal", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Proposal", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Proposal` table.
  """
  _count: Int! @fdc_generated(from: "Proposal.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Proposal` table where the `date` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  date_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Proposal.date", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Proposal` table where the `hostId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  hostId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Proposal.hostId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Proposal` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Proposal.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Proposal` table where the `location` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  location_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Proposal.location", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Proposal` table where the `meetupId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  meetupId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Proposal.meetupId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Proposal` table where the `note` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  note_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Proposal.note", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Proposal` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Proposal.status", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `date` field in the `Proposal` table.
  """
  date_min: Timestamp @fdc_generated(from: "Proposal.date", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `date` field in the `Proposal` table.
  """
  date_max: Timestamp @fdc_generated(from: "Proposal.date", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Proposal.id", purpose: ENTITY_ID)
}
extend type Tribe {
  """
  ✨ List `Meetup` objects in a one-to-many relationship (where `Meetup`.`tribe` is this object).
  """
  meetups_on_tribe(
    """
    Filter condition to narrow down the query results.
    """
    where: Meetup_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Meetup_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Meetup_Having
  ): [Meetup!]! @fdc_generated(from: "Meetup.tribe", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `TribeMember` objects in a one-to-many relationship (where `TribeMember`.`tribe` is this object).
  """
  tribeMembers_on_tribe(
    """
    Filter condition to narrow down the query results.
    """
    where: TribeMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TribeMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TribeMember_Having
  ): [TribeMember!]! @fdc_generated(from: "TribeMember.tribe", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Member` objects using `TribeMember` as the join table (a `TribeMember` object exists where its `tribe` is this and its `member` is that).
  """
  members_via_TribeMember(
    """
    Filter condition to narrow down the query results.
    """
    where: TribeMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TribeMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TribeMember_Having
  ): [Member!]! @fdc_generated(from: "TribeMember", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Tribe", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Tribe` table.
  """
  _count: Int! @fdc_generated(from: "Tribe.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tribe` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tribe.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tribe` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tribe.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tribe` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tribe.name", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Tribe.id", purpose: ENTITY_ID)
}
extend type TribeMember {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "TribeMember", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `TribeMember` table.
  """
  _count: Int! @fdc_generated(from: "TribeMember.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TribeMember` table where the `memberId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  memberId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TribeMember.memberId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TribeMember` table where the `tribeId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tribeId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TribeMember.tribeId", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "TribeMember.tribeId,memberId", purpose: ENTITY_ID)
}
extend type UserDevice {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "UserDevice", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `UserDevice` table.
  """
  _count: Int! @fdc_generated(from: "UserDevice.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserDevice` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserDevice` table where the `platform` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  platform_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice.platform", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserDevice` table where the `token` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  token_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice.token", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserDevice` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserDevice` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserDevice.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `updatedAt` field in the `UserDevice` table.
  """
  updatedAt_min: Date @fdc_generated(from: "UserDevice.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `updatedAt` field in the `UserDevice` table.
  """
  updatedAt_max: Date @fdc_generated(from: "UserDevice.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "UserDevice.id", purpose: ENTITY_ID)
}
