type Member @table(name: "member") {
  # id: UUID! @default(expr: "uuidV4()")
  name: String! @index
  email: String! @unique
  phone: String! @unique
  userId: String @col(name: "user_id") @index
  status: String! @index # e.g. "invited", "active", "inactive", "banned"
  profilePicData: String @col(name: "profile_pic_data")
  mapType: String @col(name: "map_type")
  googleId: String @col(name: "google_id") @index
  googleRefreshToken: String @col(name: "google_refresh_token")
  rootFolderId: String @col(name: "root_folder_id")
}

type MemberAlertPreference @table(name: "member_alert_preference") @unique(fields: ["memberId", "alertType"]) {
  # id: UUID! @default(expr: "uuidV4()")
  memberId: UUID! @col(name: "member_id") @index
  member: Member! @ref(fields: "memberId")
  alertType: String! @col(name: "alert_type") @index
  emailEnabled: Boolean! @col(name: "email_enabled")
  pushEnabled: Boolean! @col(name: "push_enabled")
}

type UserDevice @table(name: "user_device") {
  # id: UUID! @default(expr: "uuidV4()")
  token: String! @unique # The FCM registration token
  platform: String! # e.g. "android", "ios", "web"
  updatedAt: Date! @col(name: "updated_at") @default(expr: "request.time")
  userId: String! @col(name: "user_id") @index
}

type Tribe @table(name: "tribe") {
  # id: UUID! @default(expr: "uuidV4()")
  name: String @index
  description: String! @index
  iconType: String @col(name: "icon_type") @index
}

type TribeMember @table(name: "tribe_member") @unique(fields: ["tribeId", "memberId"]) {
  # id: UUID! @default(expr: "uuidV4()")
  tribeId: UUID! @col(name: "tribe_id") @index
  tribe: Tribe! @ref(fields: "tribeId")
  memberId: UUID! @col(name: "member_id") @index
  member: Member! @ref(fields: "memberId")
}

type Meetup @table(name: "meetup") {
  # id: UUID! @default(expr: "uuidV4()")
  creatorId: UUID! @col(name: "creator_id") @index
  creator: Member! @ref(fields: "creatorId")
  tribeId: UUID! @col(name: "tribe_id") @index
  tribe: Tribe! @ref(fields: "tribeId")
  title: String @index
  details: String @index
  status: String! @index # e.g. "Planning", "Upcoming", "Ongoing", "Cancelled", "Complete"
  createdAt: Timestamp! @col(name: "created_at") @index
  decisionMethod: String! @col(name: "decision_method") @index
  daysToDecide: Int! @col(name: "days_to_decide") @index
  recurrenceType: String @col(name: "recurrence_type") @index
  recurrenceBasis: Int @col(name: "recurrence_basis") @index
  monthToRecur: Int @col(name: "month_to_recur") @index
  weekToRecur: Int @col(name: "week_to_recur") @index
  dayToRecur: Int @col(name: "day_to_recur") @index
  recursOn: Timestamp @col(name: "recurs_on") @index
  eventType: String @col(name: "event_type") @index
  iconType: String @col(name: "icon_type") @index
  rootFolderId: String @col(name: "root_folder_id")
  leaderTitle: String @col(name: "leader_title")
}

type Proposal @table(name: "proposal") {
  # id: UUID! @default(expr: "uuidV4()")
  meetupId: UUID! @col(name: "meetup_id") @index
  meetup: Meetup! @ref(fields: "meetupId")
  hostId: UUID! @col(name: "host_id") @index
  host: Member! @ref(fields: "hostId")
  startAt: Timestamp! @col(name: "start_at") @index
  endAt: Timestamp! @col(name: "end_at") @index
  location: String! @index
  latitude: Float
  longitude: Float
  geofenceRadiusMeters: Int @col(name: "geofence_radius_meters")
  status: String! @index # e.g. "pending", "accepted", "rejected", "cancelled", "completed"
  note: String
  rootFolderId: String @col(name: "root_folder_id")
}

type MeetupEvent @table(name: "meetup_event") {
  # id: UUID! @default(expr: "uuidV4()")
  meetupId: UUID! @col(name: "meetup_id") @index
  meetup: Meetup! @ref(fields: "meetupId")
  hostId: UUID! @col(name: "host_id") @index
  host: Member! @ref(fields: "hostId")
  startAt: Timestamp! @col(name: "start_at") @index
  endAt: Timestamp! @col(name: "end_at") @index
  location: String! @index
  latitude: Float
  longitude: Float
  geofenceRadiusMeters: Int @col(name: "geofence_radius_meters")
  note: String
  rootFolderId: String @col(name: "root_folder_id")
}

type EventCheckIn @table(name: "event_check_in") {
  meetupEventId: UUID! @col(name: "meetup_event_id") @index
  meetupEvent: MeetupEvent! @ref(fields: "meetupEventId")
  memberId: UUID! @col(name: "member_id") @index
  member: Member! @ref(fields: "memberId")
  status: String! @index # "checked_in", "checked_out"
  checkInTime: Timestamp! @col(name: "check_in_time")
  checkOutTime: Timestamp @col(name: "check_out_time")
}

type Availability @table(name: "availability") {
  # id: UUID! @default(expr: "uuidV4()")
  memberId: UUID! @col(name: "member_id") @index
  member: Member! @ref(fields: "memberId")
  proposalId: UUID! @col(name: "proposal_id") @index
  proposal: Proposal! @ref(fields: "proposalId")
  status: String! @index # e.g. "unanswered", "attending", "maybe_attending", "not_attending"
  vote: Boolean # true for yes, false for no (used for single_choice_voting)
  note: String
}

type MemberContact @table(name: "member_contact") @unique(fields: ["sourceId", "subjectId"]) {
  # id: UUID! @default(expr: "uuidV4()")
  sourceId: UUID! @col(name: "source_id") @index
  source: Member! @ref(fields: "sourceId")
  subjectId: UUID! @col(name: "subject_id") @index
  subject: Member! @ref(fields: "subjectId")
  status: String! @index # e.g. "pending", "accepted"
}

type Chat @table(name: "chat") {
  # id: UUID! @default(expr: "uuidV4()")
  name: String @index
  url: String @index
  isCouncil: Boolean @col(name: "is_council")
  meetupId: UUID @col(name: "meetup_id") @index
  meetup: Meetup @ref(fields: "meetupId")
  tribeId: UUID @col(name: "tribe_id") @index
  tribe: Tribe @ref(fields: "tribeId")
}

type ChatMember @table(name: "chat_member") @unique(fields: ["chatId", "memberId"]) {
  # id: UUID! @default(expr: "uuidV4()")
  chatId: UUID! @col(name: "chat_id") @index
  chat: Chat! @ref(fields: "chatId")
  memberId: UUID! @col(name: "member_id") @index
  member: Member! @ref(fields: "memberId")
}

type Notification @table(name: "notification") {
  # id: UUID! @default(expr: "uuidV4()")
  memberId: UUID! @col(name: "member_id") @index
  member: Member! @ref(fields: "memberId")
  title: String!
  body: String!
  htmlBody: String @col(name: "html_body")
  resourceType: String @col(name: "resource_type")
  resourceId: String @col(name: "resource_id")
  actionMode: String @col(name: "action_mode")
}

type Poll @table(name: "poll") {
  creatorId: UUID! @col(name: "creator_id") @index
  creator: Member! @ref(fields: "creatorId")
  meetupId: UUID! @col(name: "meetup_id") @index
  meetup: Meetup! @ref(fields: "meetupId")
  meetupEventId: UUID @col(name: "meetup_event_id") @index
  meetupEvent: MeetupEvent @ref(fields: "meetupEventId")
  title: String!
  details: String
  status: String! @index # e.g. "Posting", "Voting", "Complete"
  rootFolderId: String @col(name: "root_folder_id")
  entryDeadline: Timestamp @col(name: "entry_deadline")
  voteDeadline: Timestamp @col(name: "vote_deadline")
  iconType: String @col(name: "icon_type")
}

type PollEntry @table(name: "poll_entry") {
  pollId: UUID! @col(name: "poll_id") @index
  poll: Poll! @ref(fields: "pollId")
  fileId: String! @col(name: "file_id")
  creatorId: UUID! @col(name: "creator_id") @index
  creator: Member! @ref(fields: "creatorId")
  caption: String
  thumbnail: String
}

type PollVote @table(name: "poll_vote") @unique(fields: ["pollId", "voterId"]) {
  pollId: UUID! @col(name: "poll_id") @index
  poll: Poll! @ref(fields: "pollId")
  voterId: UUID! @col(name: "voter_id") @index
  voter: Member! @ref(fields: "voterId")
  pollEntryId: UUID! @col(name: "poll_entry_id") @index
  pollEntry: PollEntry! @ref(fields: "pollEntryId")
}

type PollWinner @table(name: "poll_winner") @unique(fields: ["pollId", "pollEntryId"]) {
  pollId: UUID! @col(name: "poll_id") @index
  poll: Poll! @ref(fields: "pollId")
  pollEntryId: UUID! @col(name: "poll_entry_id") @index
  pollEntry: PollEntry! @ref(fields: "pollEntryId")
}

type HelpRegistry @table(name: "help_registry") {
  proposalId: UUID @col(name: "proposal_id") @index
  proposal: Proposal @ref(fields: "proposalId")
  meetupEventId: UUID @col(name: "meetup_event_id") @index
  meetupEvent: MeetupEvent @ref(fields: "meetupEventId")
  name: String!
  details: String
  isCouncil: Boolean @col(name: "is_council")
}

type RegistryItem @table(name: "registry_item") {
  helpRegistryId: UUID! @col(name: "help_registry_id") @index
  helpRegistry: HelpRegistry! @ref(fields: "helpRegistryId")
  details: String!
  helperId: UUID @col(name: "helper_id") @index
  helper: Member @ref(fields: "helperId")
  status: String! @index # e.g. "Todo", "InProgress", "Blocked", "Complete", "Cancelled"
}

type TribalCouncil @table(name: "tribal_council") @unique(fields: ["meetupId", "memberId"]) {
  id: UUID! @default(expr: "uuidV4()")
  meetupId: UUID! @col(name: "meetup_id") @index
  meetup: Meetup! @ref(fields: "meetupId")
  memberId: UUID! @col(name: "member_id") @index
  member: Member! @ref(fields: "memberId")
}