type Member @table {
  # id: UUID! @default(expr: "uuidV4()")
  name: String! @index
  email: String! @unique
  phone: String! @unique
  userId: String @index
  status: String! @index # e.g. "invited", "active", "inactive", "banned"
  profilePicData: String
  mapType: String
}

type MemberAlertPreference @table @unique(fields: ["member", "alertType"]) {
  # id: UUID! @default(expr: "uuidV4()")
  member: Member! @index
  alertType: String! @index
  emailEnabled: Boolean!
  pushEnabled: Boolean!
}

type UserDevice @table {
  # id: UUID! @default(expr: "uuidV4()")
  token: String! @unique # The FCM registration token
  platform: String! # e.g. "android", "ios", "web"
  updatedAt: Date! @default(expr: "request.time")
  userId: String! @index
}

type Tribe @table {
  # id: UUID! @default(expr: "uuidV4()")
  name: String @index
  description: String! @index
  iconType: String @index
}

type TribeMember @table @unique(fields: ["tribe", "member"]) {
  # id: UUID! @default(expr: "uuidV4()")
  tribe: Tribe! @index
  member: Member! @index
}

type Meetup @table {
  # id: UUID! @default(expr: "uuidV4()")
  creator: Member! @index
  tribe: Tribe! @index
  title: String @index
  details: String @index
  status: String! @index # e.g. "active", "cancelled", "completed"
  createdAt: Timestamp! @index
  decisionMethod: String! @index # e.g. "most_available", "single_choice_voting", etc.
  daysToDecide: Int! @index
  recursEveryDays: Int @index
  eventType: String @index
  iconType: String @index
}

type Proposal @table {
  # id: UUID! @default(expr: "uuidV4()")
  meetup: Meetup! @index
  host: Member! @index
  date: Timestamp! @index
  location: String! @index
  status: String! @index # e.g. "pending", "accepted", "rejected", "cancelled", "completed"
  note: String
}

type Availability @table {
  # id: UUID! @default(expr: "uuidV4()")
  member: Member! @index
  proposal: Proposal! @index
  status: String! @index # e.g. "unanswered", "attending", "maybe_attending", "not_attending"
  vote: Boolean # true for yes, false for no (used for single_choice_voting)
  note: String
}

type MemberContact @table @unique(fields: ["source", "subject"]) {
  # id: UUID! @default(expr: "uuidV4()")
  source: Member! @index
  subject: Member! @index
  status: String! @index # e.g. "pending", "accepted"
}

type Chat @table {
  # id: UUID! @default(expr: "uuidV4()")
  name: String @index
  url: String @index
}

type ChatMember @table @unique(fields: ["chat", "member"]) {
  # id: UUID! @default(expr: "uuidV4()")
  chat: Chat! @index
  member: Member! @index
}

type Notification @table {
  # id: UUID! @default(expr: "uuidV4()")
  member: Member! @index
  title: String!
  body: String!
  htmlBody: String
  resourceType: String
  resourceId: String
  actionMode: String
}